//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: canonical.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Skillpack_V1_CanonicalStoreServiceClient`, then call methods of this protocol to make API calls.
public protocol Skillpack_V1_CanonicalStoreServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Skillpack_V1_CanonicalStoreServiceClientInterceptorFactoryProtocol? { get }

  func syncAgents(
    _ request: Skillpack_V1_SyncAgentsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_SyncAgentsRequest, Skillpack_V1_SyncAgentsResponse>

  func checkBoundary(
    _ request: Skillpack_V1_CheckBoundaryRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_CheckBoundaryRequest, Skillpack_V1_CheckBoundaryResponse>

  func migrateAll(
    _ request: Skillpack_V1_MigrateAllRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_MigrateAllRequest, Skillpack_V1_MigrateAllResponse>

  func importSkill(
    _ request: Skillpack_V1_ImportSkillRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_ImportSkillRequest, Skillpack_V1_ImportSkillResponse>

  func promoteSkill(
    _ request: Skillpack_V1_PromoteSkillRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_PromoteSkillRequest, Skillpack_V1_PromoteSkillResponse>

  func getStatus(
    _ request: Skillpack_V1_GetStatusRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_GetStatusRequest, Skillpack_V1_GetStatusResponse>

  func syncAgentsStream(
    _ request: Skillpack_V1_SyncAgentsRequest,
    callOptions: CallOptions?,
    handler: @escaping (Skillpack_V1_SyncEvent) -> Void
  ) -> ServerStreamingCall<Skillpack_V1_SyncAgentsRequest, Skillpack_V1_SyncEvent>

  func rollbackSync(
    _ request: Skillpack_V1_RollbackSyncRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_RollbackSyncRequest, Skillpack_V1_RollbackSyncResponse>

  func packageSkill(
    _ request: Skillpack_V1_PackageSkillRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_PackageSkillRequest, Skillpack_V1_PackageSkillResponse>

  func pullSkill(
    _ request: Skillpack_V1_PullSkillRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_PullSkillRequest, Skillpack_V1_PullSkillResponse>

  func migrateSkills(
    _ request: Skillpack_V1_MigrateSkillsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_MigrateSkillsRequest, Skillpack_V1_MigrateSkillsResponse>

  func migrateAgents(
    _ request: Skillpack_V1_MigrateAgentsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_MigrateAgentsRequest, Skillpack_V1_MigrateAgentsResponse>

  func migrateClaudeAgents(
    _ request: Skillpack_V1_MigrateClaudeAgentsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_MigrateClaudeAgentsRequest, Skillpack_V1_MigrateClaudeAgentsResponse>

  func migrateHarnesses(
    _ request: Skillpack_V1_MigrateHarnessesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_MigrateHarnessesRequest, Skillpack_V1_MigrateHarnessesResponse>
}

extension Skillpack_V1_CanonicalStoreServiceClientProtocol {
  public var serviceName: String {
    return "skillpack.v1.CanonicalStoreService"
  }

  /// Trigger canonical store sync to agents
  ///
  /// - Parameters:
  ///   - request: Request to send to SyncAgents.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func syncAgents(
    _ request: Skillpack_V1_SyncAgentsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_SyncAgentsRequest, Skillpack_V1_SyncAgentsResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.syncAgents.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSyncAgentsInterceptors() ?? []
    )
  }

  /// Check IP boundary for a path or skill name
  ///
  /// - Parameters:
  ///   - request: Request to send to CheckBoundary.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func checkBoundary(
    _ request: Skillpack_V1_CheckBoundaryRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_CheckBoundaryRequest, Skillpack_V1_CheckBoundaryResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.checkBoundary.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCheckBoundaryInterceptors() ?? []
    )
  }

  /// Migrate all physical skills from agent dirs to canonical store
  ///
  /// - Parameters:
  ///   - request: Request to send to MigrateAll.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func migrateAll(
    _ request: Skillpack_V1_MigrateAllRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_MigrateAllRequest, Skillpack_V1_MigrateAllResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.migrateAll.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMigrateAllInterceptors() ?? []
    )
  }

  /// Import an external skill into canonical store
  ///
  /// - Parameters:
  ///   - request: Request to send to ImportSkill.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func importSkill(
    _ request: Skillpack_V1_ImportSkillRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_ImportSkillRequest, Skillpack_V1_ImportSkillResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.importSkill.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeImportSkillInterceptors() ?? []
    )
  }

  /// Promote a candidate skill to active canonical store
  ///
  /// - Parameters:
  ///   - request: Request to send to PromoteSkill.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func promoteSkill(
    _ request: Skillpack_V1_PromoteSkillRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_PromoteSkillRequest, Skillpack_V1_PromoteSkillResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.promoteSkill.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePromoteSkillInterceptors() ?? []
    )
  }

  /// Get canonical store status (skill count, agents, health)
  ///
  /// - Parameters:
  ///   - request: Request to send to GetStatus.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getStatus(
    _ request: Skillpack_V1_GetStatusRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_GetStatusRequest, Skillpack_V1_GetStatusResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.getStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetStatusInterceptors() ?? []
    )
  }

  /// Stream sync progress
  ///
  /// - Parameters:
  ///   - request: Request to send to SyncAgentsStream.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  public func syncAgentsStream(
    _ request: Skillpack_V1_SyncAgentsRequest,
    callOptions: CallOptions? = nil,
    handler: @escaping (Skillpack_V1_SyncEvent) -> Void
  ) -> ServerStreamingCall<Skillpack_V1_SyncAgentsRequest, Skillpack_V1_SyncEvent> {
    return self.makeServerStreamingCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.syncAgentsStream.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSyncAgentsStreamInterceptors() ?? [],
      handler: handler
    )
  }

  /// Rollback last sync for one or all agents
  ///
  /// - Parameters:
  ///   - request: Request to send to RollbackSync.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func rollbackSync(
    _ request: Skillpack_V1_RollbackSyncRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_RollbackSyncRequest, Skillpack_V1_RollbackSyncResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.rollbackSync.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRollbackSyncInterceptors() ?? []
    )
  }

  /// Package a skill as an OCI artifact for distribution
  ///
  /// - Parameters:
  ///   - request: Request to send to PackageSkill.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func packageSkill(
    _ request: Skillpack_V1_PackageSkillRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_PackageSkillRequest, Skillpack_V1_PackageSkillResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.packageSkill.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePackageSkillInterceptors() ?? []
    )
  }

  /// Pull a skill from an OCI registry
  ///
  /// - Parameters:
  ///   - request: Request to send to PullSkill.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func pullSkill(
    _ request: Skillpack_V1_PullSkillRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_PullSkillRequest, Skillpack_V1_PullSkillResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.pullSkill.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePullSkillInterceptors() ?? []
    )
  }

  /// Migrate skills in canonical store (adds missing frontmatter fields)
  ///
  /// - Parameters:
  ///   - request: Request to send to MigrateSkills.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func migrateSkills(
    _ request: Skillpack_V1_MigrateSkillsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_MigrateSkillsRequest, Skillpack_V1_MigrateSkillsResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.migrateSkills.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMigrateSkillsInterceptors() ?? []
    )
  }

  /// Migrate agent skills in ~/.config/agents/skills
  ///
  /// - Parameters:
  ///   - request: Request to send to MigrateAgents.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func migrateAgents(
    _ request: Skillpack_V1_MigrateAgentsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_MigrateAgentsRequest, Skillpack_V1_MigrateAgentsResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.migrateAgents.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMigrateAgentsInterceptors() ?? []
    )
  }

  /// Migrate Claude agent definitions in ~/.claude/agents
  ///
  /// - Parameters:
  ///   - request: Request to send to MigrateClaudeAgents.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func migrateClaudeAgents(
    _ request: Skillpack_V1_MigrateClaudeAgentsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_MigrateClaudeAgentsRequest, Skillpack_V1_MigrateClaudeAgentsResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.migrateClaudeAgents.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMigrateClaudeAgentsInterceptors() ?? []
    )
  }

  /// Migrate agent harness rules in ~/.config/agents/skills/*/rules
  ///
  /// - Parameters:
  ///   - request: Request to send to MigrateHarnesses.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func migrateHarnesses(
    _ request: Skillpack_V1_MigrateHarnessesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_MigrateHarnessesRequest, Skillpack_V1_MigrateHarnessesResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.migrateHarnesses.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMigrateHarnessesInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Skillpack_V1_CanonicalStoreServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Skillpack_V1_CanonicalStoreServiceNIOClient")
public final class Skillpack_V1_CanonicalStoreServiceClient: Skillpack_V1_CanonicalStoreServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Skillpack_V1_CanonicalStoreServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Skillpack_V1_CanonicalStoreServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the skillpack.v1.CanonicalStoreService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Skillpack_V1_CanonicalStoreServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Skillpack_V1_CanonicalStoreServiceNIOClient: Skillpack_V1_CanonicalStoreServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Skillpack_V1_CanonicalStoreServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the skillpack.v1.CanonicalStoreService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Skillpack_V1_CanonicalStoreServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Skillpack_V1_CanonicalStoreServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Skillpack_V1_CanonicalStoreServiceClientInterceptorFactoryProtocol? { get }

  func makeSyncAgentsCall(
    _ request: Skillpack_V1_SyncAgentsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_SyncAgentsRequest, Skillpack_V1_SyncAgentsResponse>

  func makeCheckBoundaryCall(
    _ request: Skillpack_V1_CheckBoundaryRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_CheckBoundaryRequest, Skillpack_V1_CheckBoundaryResponse>

  func makeMigrateAllCall(
    _ request: Skillpack_V1_MigrateAllRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_MigrateAllRequest, Skillpack_V1_MigrateAllResponse>

  func makeImportSkillCall(
    _ request: Skillpack_V1_ImportSkillRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_ImportSkillRequest, Skillpack_V1_ImportSkillResponse>

  func makePromoteSkillCall(
    _ request: Skillpack_V1_PromoteSkillRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_PromoteSkillRequest, Skillpack_V1_PromoteSkillResponse>

  func makeGetStatusCall(
    _ request: Skillpack_V1_GetStatusRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_GetStatusRequest, Skillpack_V1_GetStatusResponse>

  func makeSyncAgentsStreamCall(
    _ request: Skillpack_V1_SyncAgentsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncServerStreamingCall<Skillpack_V1_SyncAgentsRequest, Skillpack_V1_SyncEvent>

  func makeRollbackSyncCall(
    _ request: Skillpack_V1_RollbackSyncRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_RollbackSyncRequest, Skillpack_V1_RollbackSyncResponse>

  func makePackageSkillCall(
    _ request: Skillpack_V1_PackageSkillRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_PackageSkillRequest, Skillpack_V1_PackageSkillResponse>

  func makePullSkillCall(
    _ request: Skillpack_V1_PullSkillRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_PullSkillRequest, Skillpack_V1_PullSkillResponse>

  func makeMigrateSkillsCall(
    _ request: Skillpack_V1_MigrateSkillsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_MigrateSkillsRequest, Skillpack_V1_MigrateSkillsResponse>

  func makeMigrateAgentsCall(
    _ request: Skillpack_V1_MigrateAgentsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_MigrateAgentsRequest, Skillpack_V1_MigrateAgentsResponse>

  func makeMigrateClaudeAgentsCall(
    _ request: Skillpack_V1_MigrateClaudeAgentsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_MigrateClaudeAgentsRequest, Skillpack_V1_MigrateClaudeAgentsResponse>

  func makeMigrateHarnessesCall(
    _ request: Skillpack_V1_MigrateHarnessesRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_MigrateHarnessesRequest, Skillpack_V1_MigrateHarnessesResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Skillpack_V1_CanonicalStoreServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Skillpack_V1_CanonicalStoreServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Skillpack_V1_CanonicalStoreServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeSyncAgentsCall(
    _ request: Skillpack_V1_SyncAgentsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_SyncAgentsRequest, Skillpack_V1_SyncAgentsResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.syncAgents.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSyncAgentsInterceptors() ?? []
    )
  }

  public func makeCheckBoundaryCall(
    _ request: Skillpack_V1_CheckBoundaryRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_CheckBoundaryRequest, Skillpack_V1_CheckBoundaryResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.checkBoundary.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCheckBoundaryInterceptors() ?? []
    )
  }

  public func makeMigrateAllCall(
    _ request: Skillpack_V1_MigrateAllRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_MigrateAllRequest, Skillpack_V1_MigrateAllResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.migrateAll.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMigrateAllInterceptors() ?? []
    )
  }

  public func makeImportSkillCall(
    _ request: Skillpack_V1_ImportSkillRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_ImportSkillRequest, Skillpack_V1_ImportSkillResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.importSkill.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeImportSkillInterceptors() ?? []
    )
  }

  public func makePromoteSkillCall(
    _ request: Skillpack_V1_PromoteSkillRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_PromoteSkillRequest, Skillpack_V1_PromoteSkillResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.promoteSkill.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePromoteSkillInterceptors() ?? []
    )
  }

  public func makeGetStatusCall(
    _ request: Skillpack_V1_GetStatusRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_GetStatusRequest, Skillpack_V1_GetStatusResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.getStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetStatusInterceptors() ?? []
    )
  }

  public func makeSyncAgentsStreamCall(
    _ request: Skillpack_V1_SyncAgentsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncServerStreamingCall<Skillpack_V1_SyncAgentsRequest, Skillpack_V1_SyncEvent> {
    return self.makeAsyncServerStreamingCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.syncAgentsStream.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSyncAgentsStreamInterceptors() ?? []
    )
  }

  public func makeRollbackSyncCall(
    _ request: Skillpack_V1_RollbackSyncRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_RollbackSyncRequest, Skillpack_V1_RollbackSyncResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.rollbackSync.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRollbackSyncInterceptors() ?? []
    )
  }

  public func makePackageSkillCall(
    _ request: Skillpack_V1_PackageSkillRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_PackageSkillRequest, Skillpack_V1_PackageSkillResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.packageSkill.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePackageSkillInterceptors() ?? []
    )
  }

  public func makePullSkillCall(
    _ request: Skillpack_V1_PullSkillRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_PullSkillRequest, Skillpack_V1_PullSkillResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.pullSkill.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePullSkillInterceptors() ?? []
    )
  }

  public func makeMigrateSkillsCall(
    _ request: Skillpack_V1_MigrateSkillsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_MigrateSkillsRequest, Skillpack_V1_MigrateSkillsResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.migrateSkills.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMigrateSkillsInterceptors() ?? []
    )
  }

  public func makeMigrateAgentsCall(
    _ request: Skillpack_V1_MigrateAgentsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_MigrateAgentsRequest, Skillpack_V1_MigrateAgentsResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.migrateAgents.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMigrateAgentsInterceptors() ?? []
    )
  }

  public func makeMigrateClaudeAgentsCall(
    _ request: Skillpack_V1_MigrateClaudeAgentsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_MigrateClaudeAgentsRequest, Skillpack_V1_MigrateClaudeAgentsResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.migrateClaudeAgents.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMigrateClaudeAgentsInterceptors() ?? []
    )
  }

  public func makeMigrateHarnessesCall(
    _ request: Skillpack_V1_MigrateHarnessesRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_MigrateHarnessesRequest, Skillpack_V1_MigrateHarnessesResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.migrateHarnesses.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMigrateHarnessesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Skillpack_V1_CanonicalStoreServiceAsyncClientProtocol {
  public func syncAgents(
    _ request: Skillpack_V1_SyncAgentsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_SyncAgentsResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.syncAgents.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSyncAgentsInterceptors() ?? []
    )
  }

  public func checkBoundary(
    _ request: Skillpack_V1_CheckBoundaryRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_CheckBoundaryResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.checkBoundary.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCheckBoundaryInterceptors() ?? []
    )
  }

  public func migrateAll(
    _ request: Skillpack_V1_MigrateAllRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_MigrateAllResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.migrateAll.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMigrateAllInterceptors() ?? []
    )
  }

  public func importSkill(
    _ request: Skillpack_V1_ImportSkillRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_ImportSkillResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.importSkill.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeImportSkillInterceptors() ?? []
    )
  }

  public func promoteSkill(
    _ request: Skillpack_V1_PromoteSkillRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_PromoteSkillResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.promoteSkill.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePromoteSkillInterceptors() ?? []
    )
  }

  public func getStatus(
    _ request: Skillpack_V1_GetStatusRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_GetStatusResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.getStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetStatusInterceptors() ?? []
    )
  }

  public func syncAgentsStream(
    _ request: Skillpack_V1_SyncAgentsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Skillpack_V1_SyncEvent> {
    return self.performAsyncServerStreamingCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.syncAgentsStream.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSyncAgentsStreamInterceptors() ?? []
    )
  }

  public func rollbackSync(
    _ request: Skillpack_V1_RollbackSyncRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_RollbackSyncResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.rollbackSync.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRollbackSyncInterceptors() ?? []
    )
  }

  public func packageSkill(
    _ request: Skillpack_V1_PackageSkillRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_PackageSkillResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.packageSkill.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePackageSkillInterceptors() ?? []
    )
  }

  public func pullSkill(
    _ request: Skillpack_V1_PullSkillRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_PullSkillResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.pullSkill.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePullSkillInterceptors() ?? []
    )
  }

  public func migrateSkills(
    _ request: Skillpack_V1_MigrateSkillsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_MigrateSkillsResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.migrateSkills.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMigrateSkillsInterceptors() ?? []
    )
  }

  public func migrateAgents(
    _ request: Skillpack_V1_MigrateAgentsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_MigrateAgentsResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.migrateAgents.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMigrateAgentsInterceptors() ?? []
    )
  }

  public func migrateClaudeAgents(
    _ request: Skillpack_V1_MigrateClaudeAgentsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_MigrateClaudeAgentsResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.migrateClaudeAgents.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMigrateClaudeAgentsInterceptors() ?? []
    )
  }

  public func migrateHarnesses(
    _ request: Skillpack_V1_MigrateHarnessesRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_MigrateHarnessesResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.migrateHarnesses.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMigrateHarnessesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Skillpack_V1_CanonicalStoreServiceAsyncClient: Skillpack_V1_CanonicalStoreServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Skillpack_V1_CanonicalStoreServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Skillpack_V1_CanonicalStoreServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Skillpack_V1_CanonicalStoreServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'syncAgents'.
  func makeSyncAgentsInterceptors() -> [ClientInterceptor<Skillpack_V1_SyncAgentsRequest, Skillpack_V1_SyncAgentsResponse>]

  /// - Returns: Interceptors to use when invoking 'checkBoundary'.
  func makeCheckBoundaryInterceptors() -> [ClientInterceptor<Skillpack_V1_CheckBoundaryRequest, Skillpack_V1_CheckBoundaryResponse>]

  /// - Returns: Interceptors to use when invoking 'migrateAll'.
  func makeMigrateAllInterceptors() -> [ClientInterceptor<Skillpack_V1_MigrateAllRequest, Skillpack_V1_MigrateAllResponse>]

  /// - Returns: Interceptors to use when invoking 'importSkill'.
  func makeImportSkillInterceptors() -> [ClientInterceptor<Skillpack_V1_ImportSkillRequest, Skillpack_V1_ImportSkillResponse>]

  /// - Returns: Interceptors to use when invoking 'promoteSkill'.
  func makePromoteSkillInterceptors() -> [ClientInterceptor<Skillpack_V1_PromoteSkillRequest, Skillpack_V1_PromoteSkillResponse>]

  /// - Returns: Interceptors to use when invoking 'getStatus'.
  func makeGetStatusInterceptors() -> [ClientInterceptor<Skillpack_V1_GetStatusRequest, Skillpack_V1_GetStatusResponse>]

  /// - Returns: Interceptors to use when invoking 'syncAgentsStream'.
  func makeSyncAgentsStreamInterceptors() -> [ClientInterceptor<Skillpack_V1_SyncAgentsRequest, Skillpack_V1_SyncEvent>]

  /// - Returns: Interceptors to use when invoking 'rollbackSync'.
  func makeRollbackSyncInterceptors() -> [ClientInterceptor<Skillpack_V1_RollbackSyncRequest, Skillpack_V1_RollbackSyncResponse>]

  /// - Returns: Interceptors to use when invoking 'packageSkill'.
  func makePackageSkillInterceptors() -> [ClientInterceptor<Skillpack_V1_PackageSkillRequest, Skillpack_V1_PackageSkillResponse>]

  /// - Returns: Interceptors to use when invoking 'pullSkill'.
  func makePullSkillInterceptors() -> [ClientInterceptor<Skillpack_V1_PullSkillRequest, Skillpack_V1_PullSkillResponse>]

  /// - Returns: Interceptors to use when invoking 'migrateSkills'.
  func makeMigrateSkillsInterceptors() -> [ClientInterceptor<Skillpack_V1_MigrateSkillsRequest, Skillpack_V1_MigrateSkillsResponse>]

  /// - Returns: Interceptors to use when invoking 'migrateAgents'.
  func makeMigrateAgentsInterceptors() -> [ClientInterceptor<Skillpack_V1_MigrateAgentsRequest, Skillpack_V1_MigrateAgentsResponse>]

  /// - Returns: Interceptors to use when invoking 'migrateClaudeAgents'.
  func makeMigrateClaudeAgentsInterceptors() -> [ClientInterceptor<Skillpack_V1_MigrateClaudeAgentsRequest, Skillpack_V1_MigrateClaudeAgentsResponse>]

  /// - Returns: Interceptors to use when invoking 'migrateHarnesses'.
  func makeMigrateHarnessesInterceptors() -> [ClientInterceptor<Skillpack_V1_MigrateHarnessesRequest, Skillpack_V1_MigrateHarnessesResponse>]
}

public enum Skillpack_V1_CanonicalStoreServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "CanonicalStoreService",
    fullName: "skillpack.v1.CanonicalStoreService",
    methods: [
      Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.syncAgents,
      Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.checkBoundary,
      Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.migrateAll,
      Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.importSkill,
      Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.promoteSkill,
      Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.getStatus,
      Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.syncAgentsStream,
      Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.rollbackSync,
      Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.packageSkill,
      Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.pullSkill,
      Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.migrateSkills,
      Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.migrateAgents,
      Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.migrateClaudeAgents,
      Skillpack_V1_CanonicalStoreServiceClientMetadata.Methods.migrateHarnesses,
    ]
  )

  public enum Methods {
    public static let syncAgents = GRPCMethodDescriptor(
      name: "SyncAgents",
      path: "/skillpack.v1.CanonicalStoreService/SyncAgents",
      type: GRPCCallType.unary
    )

    public static let checkBoundary = GRPCMethodDescriptor(
      name: "CheckBoundary",
      path: "/skillpack.v1.CanonicalStoreService/CheckBoundary",
      type: GRPCCallType.unary
    )

    public static let migrateAll = GRPCMethodDescriptor(
      name: "MigrateAll",
      path: "/skillpack.v1.CanonicalStoreService/MigrateAll",
      type: GRPCCallType.unary
    )

    public static let importSkill = GRPCMethodDescriptor(
      name: "ImportSkill",
      path: "/skillpack.v1.CanonicalStoreService/ImportSkill",
      type: GRPCCallType.unary
    )

    public static let promoteSkill = GRPCMethodDescriptor(
      name: "PromoteSkill",
      path: "/skillpack.v1.CanonicalStoreService/PromoteSkill",
      type: GRPCCallType.unary
    )

    public static let getStatus = GRPCMethodDescriptor(
      name: "GetStatus",
      path: "/skillpack.v1.CanonicalStoreService/GetStatus",
      type: GRPCCallType.unary
    )

    public static let syncAgentsStream = GRPCMethodDescriptor(
      name: "SyncAgentsStream",
      path: "/skillpack.v1.CanonicalStoreService/SyncAgentsStream",
      type: GRPCCallType.serverStreaming
    )

    public static let rollbackSync = GRPCMethodDescriptor(
      name: "RollbackSync",
      path: "/skillpack.v1.CanonicalStoreService/RollbackSync",
      type: GRPCCallType.unary
    )

    public static let packageSkill = GRPCMethodDescriptor(
      name: "PackageSkill",
      path: "/skillpack.v1.CanonicalStoreService/PackageSkill",
      type: GRPCCallType.unary
    )

    public static let pullSkill = GRPCMethodDescriptor(
      name: "PullSkill",
      path: "/skillpack.v1.CanonicalStoreService/PullSkill",
      type: GRPCCallType.unary
    )

    public static let migrateSkills = GRPCMethodDescriptor(
      name: "MigrateSkills",
      path: "/skillpack.v1.CanonicalStoreService/MigrateSkills",
      type: GRPCCallType.unary
    )

    public static let migrateAgents = GRPCMethodDescriptor(
      name: "MigrateAgents",
      path: "/skillpack.v1.CanonicalStoreService/MigrateAgents",
      type: GRPCCallType.unary
    )

    public static let migrateClaudeAgents = GRPCMethodDescriptor(
      name: "MigrateClaudeAgents",
      path: "/skillpack.v1.CanonicalStoreService/MigrateClaudeAgents",
      type: GRPCCallType.unary
    )

    public static let migrateHarnesses = GRPCMethodDescriptor(
      name: "MigrateHarnesses",
      path: "/skillpack.v1.CanonicalStoreService/MigrateHarnesses",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Skillpack_V1_CanonicalStoreServiceProvider: CallHandlerProvider {
  var interceptors: Skillpack_V1_CanonicalStoreServiceServerInterceptorFactoryProtocol? { get }

  /// Trigger canonical store sync to agents
  func syncAgents(request: Skillpack_V1_SyncAgentsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_SyncAgentsResponse>

  /// Check IP boundary for a path or skill name
  func checkBoundary(request: Skillpack_V1_CheckBoundaryRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_CheckBoundaryResponse>

  /// Migrate all physical skills from agent dirs to canonical store
  func migrateAll(request: Skillpack_V1_MigrateAllRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_MigrateAllResponse>

  /// Import an external skill into canonical store
  func importSkill(request: Skillpack_V1_ImportSkillRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_ImportSkillResponse>

  /// Promote a candidate skill to active canonical store
  func promoteSkill(request: Skillpack_V1_PromoteSkillRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_PromoteSkillResponse>

  /// Get canonical store status (skill count, agents, health)
  func getStatus(request: Skillpack_V1_GetStatusRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_GetStatusResponse>

  /// Stream sync progress
  func syncAgentsStream(request: Skillpack_V1_SyncAgentsRequest, context: StreamingResponseCallContext<Skillpack_V1_SyncEvent>) -> EventLoopFuture<GRPCStatus>

  /// Rollback last sync for one or all agents
  func rollbackSync(request: Skillpack_V1_RollbackSyncRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_RollbackSyncResponse>

  /// Package a skill as an OCI artifact for distribution
  func packageSkill(request: Skillpack_V1_PackageSkillRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_PackageSkillResponse>

  /// Pull a skill from an OCI registry
  func pullSkill(request: Skillpack_V1_PullSkillRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_PullSkillResponse>

  /// Migrate skills in canonical store (adds missing frontmatter fields)
  func migrateSkills(request: Skillpack_V1_MigrateSkillsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_MigrateSkillsResponse>

  /// Migrate agent skills in ~/.config/agents/skills
  func migrateAgents(request: Skillpack_V1_MigrateAgentsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_MigrateAgentsResponse>

  /// Migrate Claude agent definitions in ~/.claude/agents
  func migrateClaudeAgents(request: Skillpack_V1_MigrateClaudeAgentsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_MigrateClaudeAgentsResponse>

  /// Migrate agent harness rules in ~/.config/agents/skills/*/rules
  func migrateHarnesses(request: Skillpack_V1_MigrateHarnessesRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_MigrateHarnessesResponse>
}

extension Skillpack_V1_CanonicalStoreServiceProvider {
  public var serviceName: Substring {
    return Skillpack_V1_CanonicalStoreServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "SyncAgents":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_SyncAgentsRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_SyncAgentsResponse>(),
        interceptors: self.interceptors?.makeSyncAgentsInterceptors() ?? [],
        userFunction: self.syncAgents(request:context:)
      )

    case "CheckBoundary":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_CheckBoundaryRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_CheckBoundaryResponse>(),
        interceptors: self.interceptors?.makeCheckBoundaryInterceptors() ?? [],
        userFunction: self.checkBoundary(request:context:)
      )

    case "MigrateAll":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_MigrateAllRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_MigrateAllResponse>(),
        interceptors: self.interceptors?.makeMigrateAllInterceptors() ?? [],
        userFunction: self.migrateAll(request:context:)
      )

    case "ImportSkill":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_ImportSkillRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_ImportSkillResponse>(),
        interceptors: self.interceptors?.makeImportSkillInterceptors() ?? [],
        userFunction: self.importSkill(request:context:)
      )

    case "PromoteSkill":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_PromoteSkillRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_PromoteSkillResponse>(),
        interceptors: self.interceptors?.makePromoteSkillInterceptors() ?? [],
        userFunction: self.promoteSkill(request:context:)
      )

    case "GetStatus":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_GetStatusRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_GetStatusResponse>(),
        interceptors: self.interceptors?.makeGetStatusInterceptors() ?? [],
        userFunction: self.getStatus(request:context:)
      )

    case "SyncAgentsStream":
      return ServerStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_SyncAgentsRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_SyncEvent>(),
        interceptors: self.interceptors?.makeSyncAgentsStreamInterceptors() ?? [],
        userFunction: self.syncAgentsStream(request:context:)
      )

    case "RollbackSync":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_RollbackSyncRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_RollbackSyncResponse>(),
        interceptors: self.interceptors?.makeRollbackSyncInterceptors() ?? [],
        userFunction: self.rollbackSync(request:context:)
      )

    case "PackageSkill":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_PackageSkillRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_PackageSkillResponse>(),
        interceptors: self.interceptors?.makePackageSkillInterceptors() ?? [],
        userFunction: self.packageSkill(request:context:)
      )

    case "PullSkill":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_PullSkillRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_PullSkillResponse>(),
        interceptors: self.interceptors?.makePullSkillInterceptors() ?? [],
        userFunction: self.pullSkill(request:context:)
      )

    case "MigrateSkills":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_MigrateSkillsRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_MigrateSkillsResponse>(),
        interceptors: self.interceptors?.makeMigrateSkillsInterceptors() ?? [],
        userFunction: self.migrateSkills(request:context:)
      )

    case "MigrateAgents":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_MigrateAgentsRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_MigrateAgentsResponse>(),
        interceptors: self.interceptors?.makeMigrateAgentsInterceptors() ?? [],
        userFunction: self.migrateAgents(request:context:)
      )

    case "MigrateClaudeAgents":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_MigrateClaudeAgentsRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_MigrateClaudeAgentsResponse>(),
        interceptors: self.interceptors?.makeMigrateClaudeAgentsInterceptors() ?? [],
        userFunction: self.migrateClaudeAgents(request:context:)
      )

    case "MigrateHarnesses":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_MigrateHarnessesRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_MigrateHarnessesResponse>(),
        interceptors: self.interceptors?.makeMigrateHarnessesInterceptors() ?? [],
        userFunction: self.migrateHarnesses(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Skillpack_V1_CanonicalStoreServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Skillpack_V1_CanonicalStoreServiceServerInterceptorFactoryProtocol? { get }

  /// Trigger canonical store sync to agents
  func syncAgents(
    request: Skillpack_V1_SyncAgentsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_SyncAgentsResponse

  /// Check IP boundary for a path or skill name
  func checkBoundary(
    request: Skillpack_V1_CheckBoundaryRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_CheckBoundaryResponse

  /// Migrate all physical skills from agent dirs to canonical store
  func migrateAll(
    request: Skillpack_V1_MigrateAllRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_MigrateAllResponse

  /// Import an external skill into canonical store
  func importSkill(
    request: Skillpack_V1_ImportSkillRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_ImportSkillResponse

  /// Promote a candidate skill to active canonical store
  func promoteSkill(
    request: Skillpack_V1_PromoteSkillRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_PromoteSkillResponse

  /// Get canonical store status (skill count, agents, health)
  func getStatus(
    request: Skillpack_V1_GetStatusRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_GetStatusResponse

  /// Stream sync progress
  func syncAgentsStream(
    request: Skillpack_V1_SyncAgentsRequest,
    responseStream: GRPCAsyncResponseStreamWriter<Skillpack_V1_SyncEvent>,
    context: GRPCAsyncServerCallContext
  ) async throws

  /// Rollback last sync for one or all agents
  func rollbackSync(
    request: Skillpack_V1_RollbackSyncRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_RollbackSyncResponse

  /// Package a skill as an OCI artifact for distribution
  func packageSkill(
    request: Skillpack_V1_PackageSkillRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_PackageSkillResponse

  /// Pull a skill from an OCI registry
  func pullSkill(
    request: Skillpack_V1_PullSkillRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_PullSkillResponse

  /// Migrate skills in canonical store (adds missing frontmatter fields)
  func migrateSkills(
    request: Skillpack_V1_MigrateSkillsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_MigrateSkillsResponse

  /// Migrate agent skills in ~/.config/agents/skills
  func migrateAgents(
    request: Skillpack_V1_MigrateAgentsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_MigrateAgentsResponse

  /// Migrate Claude agent definitions in ~/.claude/agents
  func migrateClaudeAgents(
    request: Skillpack_V1_MigrateClaudeAgentsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_MigrateClaudeAgentsResponse

  /// Migrate agent harness rules in ~/.config/agents/skills/*/rules
  func migrateHarnesses(
    request: Skillpack_V1_MigrateHarnessesRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_MigrateHarnessesResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Skillpack_V1_CanonicalStoreServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Skillpack_V1_CanonicalStoreServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Skillpack_V1_CanonicalStoreServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Skillpack_V1_CanonicalStoreServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "SyncAgents":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_SyncAgentsRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_SyncAgentsResponse>(),
        interceptors: self.interceptors?.makeSyncAgentsInterceptors() ?? [],
        wrapping: { try await self.syncAgents(request: $0, context: $1) }
      )

    case "CheckBoundary":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_CheckBoundaryRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_CheckBoundaryResponse>(),
        interceptors: self.interceptors?.makeCheckBoundaryInterceptors() ?? [],
        wrapping: { try await self.checkBoundary(request: $0, context: $1) }
      )

    case "MigrateAll":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_MigrateAllRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_MigrateAllResponse>(),
        interceptors: self.interceptors?.makeMigrateAllInterceptors() ?? [],
        wrapping: { try await self.migrateAll(request: $0, context: $1) }
      )

    case "ImportSkill":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_ImportSkillRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_ImportSkillResponse>(),
        interceptors: self.interceptors?.makeImportSkillInterceptors() ?? [],
        wrapping: { try await self.importSkill(request: $0, context: $1) }
      )

    case "PromoteSkill":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_PromoteSkillRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_PromoteSkillResponse>(),
        interceptors: self.interceptors?.makePromoteSkillInterceptors() ?? [],
        wrapping: { try await self.promoteSkill(request: $0, context: $1) }
      )

    case "GetStatus":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_GetStatusRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_GetStatusResponse>(),
        interceptors: self.interceptors?.makeGetStatusInterceptors() ?? [],
        wrapping: { try await self.getStatus(request: $0, context: $1) }
      )

    case "SyncAgentsStream":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_SyncAgentsRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_SyncEvent>(),
        interceptors: self.interceptors?.makeSyncAgentsStreamInterceptors() ?? [],
        wrapping: { try await self.syncAgentsStream(request: $0, responseStream: $1, context: $2) }
      )

    case "RollbackSync":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_RollbackSyncRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_RollbackSyncResponse>(),
        interceptors: self.interceptors?.makeRollbackSyncInterceptors() ?? [],
        wrapping: { try await self.rollbackSync(request: $0, context: $1) }
      )

    case "PackageSkill":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_PackageSkillRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_PackageSkillResponse>(),
        interceptors: self.interceptors?.makePackageSkillInterceptors() ?? [],
        wrapping: { try await self.packageSkill(request: $0, context: $1) }
      )

    case "PullSkill":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_PullSkillRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_PullSkillResponse>(),
        interceptors: self.interceptors?.makePullSkillInterceptors() ?? [],
        wrapping: { try await self.pullSkill(request: $0, context: $1) }
      )

    case "MigrateSkills":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_MigrateSkillsRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_MigrateSkillsResponse>(),
        interceptors: self.interceptors?.makeMigrateSkillsInterceptors() ?? [],
        wrapping: { try await self.migrateSkills(request: $0, context: $1) }
      )

    case "MigrateAgents":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_MigrateAgentsRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_MigrateAgentsResponse>(),
        interceptors: self.interceptors?.makeMigrateAgentsInterceptors() ?? [],
        wrapping: { try await self.migrateAgents(request: $0, context: $1) }
      )

    case "MigrateClaudeAgents":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_MigrateClaudeAgentsRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_MigrateClaudeAgentsResponse>(),
        interceptors: self.interceptors?.makeMigrateClaudeAgentsInterceptors() ?? [],
        wrapping: { try await self.migrateClaudeAgents(request: $0, context: $1) }
      )

    case "MigrateHarnesses":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_MigrateHarnessesRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_MigrateHarnessesResponse>(),
        interceptors: self.interceptors?.makeMigrateHarnessesInterceptors() ?? [],
        wrapping: { try await self.migrateHarnesses(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol Skillpack_V1_CanonicalStoreServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'syncAgents'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSyncAgentsInterceptors() -> [ServerInterceptor<Skillpack_V1_SyncAgentsRequest, Skillpack_V1_SyncAgentsResponse>]

  /// - Returns: Interceptors to use when handling 'checkBoundary'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCheckBoundaryInterceptors() -> [ServerInterceptor<Skillpack_V1_CheckBoundaryRequest, Skillpack_V1_CheckBoundaryResponse>]

  /// - Returns: Interceptors to use when handling 'migrateAll'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMigrateAllInterceptors() -> [ServerInterceptor<Skillpack_V1_MigrateAllRequest, Skillpack_V1_MigrateAllResponse>]

  /// - Returns: Interceptors to use when handling 'importSkill'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeImportSkillInterceptors() -> [ServerInterceptor<Skillpack_V1_ImportSkillRequest, Skillpack_V1_ImportSkillResponse>]

  /// - Returns: Interceptors to use when handling 'promoteSkill'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makePromoteSkillInterceptors() -> [ServerInterceptor<Skillpack_V1_PromoteSkillRequest, Skillpack_V1_PromoteSkillResponse>]

  /// - Returns: Interceptors to use when handling 'getStatus'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetStatusInterceptors() -> [ServerInterceptor<Skillpack_V1_GetStatusRequest, Skillpack_V1_GetStatusResponse>]

  /// - Returns: Interceptors to use when handling 'syncAgentsStream'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSyncAgentsStreamInterceptors() -> [ServerInterceptor<Skillpack_V1_SyncAgentsRequest, Skillpack_V1_SyncEvent>]

  /// - Returns: Interceptors to use when handling 'rollbackSync'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeRollbackSyncInterceptors() -> [ServerInterceptor<Skillpack_V1_RollbackSyncRequest, Skillpack_V1_RollbackSyncResponse>]

  /// - Returns: Interceptors to use when handling 'packageSkill'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makePackageSkillInterceptors() -> [ServerInterceptor<Skillpack_V1_PackageSkillRequest, Skillpack_V1_PackageSkillResponse>]

  /// - Returns: Interceptors to use when handling 'pullSkill'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makePullSkillInterceptors() -> [ServerInterceptor<Skillpack_V1_PullSkillRequest, Skillpack_V1_PullSkillResponse>]

  /// - Returns: Interceptors to use when handling 'migrateSkills'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMigrateSkillsInterceptors() -> [ServerInterceptor<Skillpack_V1_MigrateSkillsRequest, Skillpack_V1_MigrateSkillsResponse>]

  /// - Returns: Interceptors to use when handling 'migrateAgents'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMigrateAgentsInterceptors() -> [ServerInterceptor<Skillpack_V1_MigrateAgentsRequest, Skillpack_V1_MigrateAgentsResponse>]

  /// - Returns: Interceptors to use when handling 'migrateClaudeAgents'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMigrateClaudeAgentsInterceptors() -> [ServerInterceptor<Skillpack_V1_MigrateClaudeAgentsRequest, Skillpack_V1_MigrateClaudeAgentsResponse>]

  /// - Returns: Interceptors to use when handling 'migrateHarnesses'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMigrateHarnessesInterceptors() -> [ServerInterceptor<Skillpack_V1_MigrateHarnessesRequest, Skillpack_V1_MigrateHarnessesResponse>]
}

public enum Skillpack_V1_CanonicalStoreServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "CanonicalStoreService",
    fullName: "skillpack.v1.CanonicalStoreService",
    methods: [
      Skillpack_V1_CanonicalStoreServiceServerMetadata.Methods.syncAgents,
      Skillpack_V1_CanonicalStoreServiceServerMetadata.Methods.checkBoundary,
      Skillpack_V1_CanonicalStoreServiceServerMetadata.Methods.migrateAll,
      Skillpack_V1_CanonicalStoreServiceServerMetadata.Methods.importSkill,
      Skillpack_V1_CanonicalStoreServiceServerMetadata.Methods.promoteSkill,
      Skillpack_V1_CanonicalStoreServiceServerMetadata.Methods.getStatus,
      Skillpack_V1_CanonicalStoreServiceServerMetadata.Methods.syncAgentsStream,
      Skillpack_V1_CanonicalStoreServiceServerMetadata.Methods.rollbackSync,
      Skillpack_V1_CanonicalStoreServiceServerMetadata.Methods.packageSkill,
      Skillpack_V1_CanonicalStoreServiceServerMetadata.Methods.pullSkill,
      Skillpack_V1_CanonicalStoreServiceServerMetadata.Methods.migrateSkills,
      Skillpack_V1_CanonicalStoreServiceServerMetadata.Methods.migrateAgents,
      Skillpack_V1_CanonicalStoreServiceServerMetadata.Methods.migrateClaudeAgents,
      Skillpack_V1_CanonicalStoreServiceServerMetadata.Methods.migrateHarnesses,
    ]
  )

  public enum Methods {
    public static let syncAgents = GRPCMethodDescriptor(
      name: "SyncAgents",
      path: "/skillpack.v1.CanonicalStoreService/SyncAgents",
      type: GRPCCallType.unary
    )

    public static let checkBoundary = GRPCMethodDescriptor(
      name: "CheckBoundary",
      path: "/skillpack.v1.CanonicalStoreService/CheckBoundary",
      type: GRPCCallType.unary
    )

    public static let migrateAll = GRPCMethodDescriptor(
      name: "MigrateAll",
      path: "/skillpack.v1.CanonicalStoreService/MigrateAll",
      type: GRPCCallType.unary
    )

    public static let importSkill = GRPCMethodDescriptor(
      name: "ImportSkill",
      path: "/skillpack.v1.CanonicalStoreService/ImportSkill",
      type: GRPCCallType.unary
    )

    public static let promoteSkill = GRPCMethodDescriptor(
      name: "PromoteSkill",
      path: "/skillpack.v1.CanonicalStoreService/PromoteSkill",
      type: GRPCCallType.unary
    )

    public static let getStatus = GRPCMethodDescriptor(
      name: "GetStatus",
      path: "/skillpack.v1.CanonicalStoreService/GetStatus",
      type: GRPCCallType.unary
    )

    public static let syncAgentsStream = GRPCMethodDescriptor(
      name: "SyncAgentsStream",
      path: "/skillpack.v1.CanonicalStoreService/SyncAgentsStream",
      type: GRPCCallType.serverStreaming
    )

    public static let rollbackSync = GRPCMethodDescriptor(
      name: "RollbackSync",
      path: "/skillpack.v1.CanonicalStoreService/RollbackSync",
      type: GRPCCallType.unary
    )

    public static let packageSkill = GRPCMethodDescriptor(
      name: "PackageSkill",
      path: "/skillpack.v1.CanonicalStoreService/PackageSkill",
      type: GRPCCallType.unary
    )

    public static let pullSkill = GRPCMethodDescriptor(
      name: "PullSkill",
      path: "/skillpack.v1.CanonicalStoreService/PullSkill",
      type: GRPCCallType.unary
    )

    public static let migrateSkills = GRPCMethodDescriptor(
      name: "MigrateSkills",
      path: "/skillpack.v1.CanonicalStoreService/MigrateSkills",
      type: GRPCCallType.unary
    )

    public static let migrateAgents = GRPCMethodDescriptor(
      name: "MigrateAgents",
      path: "/skillpack.v1.CanonicalStoreService/MigrateAgents",
      type: GRPCCallType.unary
    )

    public static let migrateClaudeAgents = GRPCMethodDescriptor(
      name: "MigrateClaudeAgents",
      path: "/skillpack.v1.CanonicalStoreService/MigrateClaudeAgents",
      type: GRPCCallType.unary
    )

    public static let migrateHarnesses = GRPCMethodDescriptor(
      name: "MigrateHarnesses",
      path: "/skillpack.v1.CanonicalStoreService/MigrateHarnesses",
      type: GRPCCallType.unary
    )
  }
}
