// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: canonical.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Skillpack_V1_MigrateOutcome: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case migrated // = 1
  case replacedWithLink // = 2
  case skippedAlreadyLinked // = 3
  case skippedIpViolation // = 4
  case failed // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .migrated
    case 2: self = .replacedWithLink
    case 3: self = .skippedAlreadyLinked
    case 4: self = .skippedIpViolation
    case 5: self = .failed
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .migrated: return 1
    case .replacedWithLink: return 2
    case .skippedAlreadyLinked: return 3
    case .skippedIpViolation: return 4
    case .failed: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Skillpack_V1_MigrateOutcome] = [
    .unspecified,
    .migrated,
    .replacedWithLink,
    .skippedAlreadyLinked,
    .skippedIpViolation,
    .failed,
  ]

}

public nonisolated enum Skillpack_V1_AgentIntegrationType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case symlink // = 1
  case indexFile // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .symlink
    case 2: self = .indexFile
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .symlink: return 1
    case .indexFile: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Skillpack_V1_AgentIntegrationType] = [
    .unspecified,
    .symlink,
    .indexFile,
  ]

}

public nonisolated struct Skillpack_V1_SyncAgentsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var dryRun: Bool = false

  public var noIndex: Bool = false

  public var onlyAgent: String {
    get {_onlyAgent ?? String()}
    set {_onlyAgent = newValue}
  }
  /// Returns true if `onlyAgent` has been explicitly set.
  public var hasOnlyAgent: Bool {self._onlyAgent != nil}
  /// Clears the value of `onlyAgent`. Subsequent reads from it will return its default value.
  public mutating func clearOnlyAgent() {self._onlyAgent = nil}

  public var namespace: String {
    get {_namespace ?? String()}
    set {_namespace = newValue}
  }
  /// Returns true if `namespace` has been explicitly set.
  public var hasNamespace: Bool {self._namespace != nil}
  /// Clears the value of `namespace`. Subsequent reads from it will return its default value.
  public mutating func clearNamespace() {self._namespace = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _onlyAgent: String? = nil
  fileprivate var _namespace: String? = nil
}

public nonisolated struct Skillpack_V1_SyncAgentsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var success: Bool = false

  public var message: String = String()

  public var skillsProcessed: Int32 = 0

  public var agentResults: [Skillpack_V1_AgentSyncResult] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_AgentSyncResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var agentName: String = String()

  public var success: Bool = false

  public var message: String = String()

  public var skillsSynced: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_CheckBoundaryRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var targetPath: String = String()

  public var skillName: String {
    get {_skillName ?? String()}
    set {_skillName = newValue}
  }
  /// Returns true if `skillName` has been explicitly set.
  public var hasSkillName: Bool {self._skillName != nil}
  /// Clears the value of `skillName`. Subsequent reads from it will return its default value.
  public mutating func clearSkillName() {self._skillName = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _skillName: String? = nil
}

public nonisolated struct Skillpack_V1_CheckBoundaryResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var isSafe: Bool = false

  public var message: String = String()

  public var violations: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_MigrateAllRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var canonicalRoot: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_MigrateAllResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var success: Bool = false

  public var message: String = String()

  public var results: [Skillpack_V1_MigrateResult] = []

  public var migratedCount: Int32 = 0

  public var replacedCount: Int32 = 0

  public var skippedLinkedCount: Int32 = 0

  public var skippedIpCount: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_MigrateResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var agentName: String = String()

  public var skillName: String = String()

  public var sourcePath: String = String()

  public var outcome: Skillpack_V1_MigrateOutcome = .unspecified

  public var message: String {
    get {_message ?? String()}
    set {_message = newValue}
  }
  /// Returns true if `message` has been explicitly set.
  public var hasMessage: Bool {self._message != nil}
  /// Clears the value of `message`. Subsequent reads from it will return its default value.
  public mutating func clearMessage() {self._message = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _message: String? = nil
}

public nonisolated struct Skillpack_V1_ImportSkillRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sourcePath: String = String()

  public var targetName: String {
    get {_targetName ?? String()}
    set {_targetName = newValue}
  }
  /// Returns true if `targetName` has been explicitly set.
  public var hasTargetName: Bool {self._targetName != nil}
  /// Clears the value of `targetName`. Subsequent reads from it will return its default value.
  public mutating func clearTargetName() {self._targetName = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _targetName: String? = nil
}

public nonisolated struct Skillpack_V1_ImportSkillResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var success: Bool = false

  public var message: String = String()

  public var skillName: String = String()

  public var canonicalPath: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_PromoteSkillRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var candidateName: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_PromoteSkillResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var success: Bool = false

  public var message: String = String()

  public var skillName: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_GetStatusRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_GetStatusResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var canonicalRoot: String = String()

  public var totalSkills: Int32 = 0

  public var activeAgents: [Skillpack_V1_AgentStatus] = []

  public var isHealthy: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_AgentStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var path: String = String()

  public var integrationType: Skillpack_V1_AgentIntegrationType = .unspecified

  public var isActive: Bool = false

  public var skillsCount: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_SyncEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var event: Skillpack_V1_SyncEvent.OneOf_Event? = nil

  public var progress: Skillpack_V1_SyncProgress {
    get {
      if case .progress(let v)? = event {return v}
      return Skillpack_V1_SyncProgress()
    }
    set {event = .progress(newValue)}
  }

  public var complete: Skillpack_V1_SyncComplete {
    get {
      if case .complete(let v)? = event {return v}
      return Skillpack_V1_SyncComplete()
    }
    set {event = .complete(newValue)}
  }

  public var error: Skillpack_V1_SyncError {
    get {
      if case .error(let v)? = event {return v}
      return Skillpack_V1_SyncError()
    }
    set {event = .error(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Event: Equatable, Sendable {
    case progress(Skillpack_V1_SyncProgress)
    case complete(Skillpack_V1_SyncComplete)
    case error(Skillpack_V1_SyncError)

  }

  public init() {}
}

public nonisolated struct Skillpack_V1_SyncProgress: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var agentName: String = String()

  public var skillName: String = String()

  public var status: String = String()

  public var current: Int32 = 0

  public var total: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_SyncComplete: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var success: Bool = false

  public var message: String = String()

  public var skillsProcessed: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_SyncError: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var agentName: String = String()

  public var skillName: String = String()

  public var errorMessage: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_RollbackSyncRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var agentName: String {
    get {_agentName ?? String()}
    set {_agentName = newValue}
  }
  /// Returns true if `agentName` has been explicitly set.
  public var hasAgentName: Bool {self._agentName != nil}
  /// Clears the value of `agentName`. Subsequent reads from it will return its default value.
  public mutating func clearAgentName() {self._agentName = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _agentName: String? = nil
}

public nonisolated struct Skillpack_V1_RollbackSyncResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var success: Bool = false

  public var message: String = String()

  public var restoredAgents: [String] = []

  public var removedSkills: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_PackageSkillRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var skillRef: String = String()

  public var registryURL: String {
    get {_registryURL ?? String()}
    set {_registryURL = newValue}
  }
  /// Returns true if `registryURL` has been explicitly set.
  public var hasRegistryURL: Bool {self._registryURL != nil}
  /// Clears the value of `registryURL`. Subsequent reads from it will return its default value.
  public mutating func clearRegistryURL() {self._registryURL = nil}

  public var namespace: String {
    get {_namespace ?? String()}
    set {_namespace = newValue}
  }
  /// Returns true if `namespace` has been explicitly set.
  public var hasNamespace: Bool {self._namespace != nil}
  /// Clears the value of `namespace`. Subsequent reads from it will return its default value.
  public mutating func clearNamespace() {self._namespace = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _registryURL: String? = nil
  fileprivate var _namespace: String? = nil
}

public nonisolated struct Skillpack_V1_PackageSkillResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var success: Bool = false

  public var message: String = String()

  public var artifactDigest: String = String()

  public var manifestURL: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_PullSkillRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var skillRef: String = String()

  public var sourceRegistry: String = String()

  public var namespace: String {
    get {_namespace ?? String()}
    set {_namespace = newValue}
  }
  /// Returns true if `namespace` has been explicitly set.
  public var hasNamespace: Bool {self._namespace != nil}
  /// Clears the value of `namespace`. Subsequent reads from it will return its default value.
  public mutating func clearNamespace() {self._namespace = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _namespace: String? = nil
}

public nonisolated struct Skillpack_V1_PullSkillResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var success: Bool = false

  public var message: String = String()

  public var localPath: String = String()

  public var skillName: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_MigrateSkillsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var canonicalRoot: String {
    get {_canonicalRoot ?? String()}
    set {_canonicalRoot = newValue}
  }
  /// Returns true if `canonicalRoot` has been explicitly set.
  public var hasCanonicalRoot: Bool {self._canonicalRoot != nil}
  /// Clears the value of `canonicalRoot`. Subsequent reads from it will return its default value.
  public mutating func clearCanonicalRoot() {self._canonicalRoot = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _canonicalRoot: String? = nil
}

public nonisolated struct Skillpack_V1_MigrateSkillsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var success: Bool = false

  public var message: String = String()

  public var totalScanned: Int32 = 0

  public var migratedCount: Int32 = 0

  public var alreadyCompliantCount: Int32 = 0

  public var migratedNames: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_MigrateAgentsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_MigrateAgentsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var success: Bool = false

  public var message: String = String()

  public var totalScanned: Int32 = 0

  public var migratedCount: Int32 = 0

  public var alreadyCompliantCount: Int32 = 0

  public var migratedNames: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_MigrateClaudeAgentsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var agentsDir: String {
    get {_agentsDir ?? String()}
    set {_agentsDir = newValue}
  }
  /// Returns true if `agentsDir` has been explicitly set.
  public var hasAgentsDir: Bool {self._agentsDir != nil}
  /// Clears the value of `agentsDir`. Subsequent reads from it will return its default value.
  public mutating func clearAgentsDir() {self._agentsDir = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _agentsDir: String? = nil
}

public nonisolated struct Skillpack_V1_MigrateClaudeAgentsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var success: Bool = false

  public var message: String = String()

  public var totalScanned: Int32 = 0

  public var migratedCount: Int32 = 0

  public var alreadyCompliantCount: Int32 = 0

  public var migratedNames: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_MigrateHarnessesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Skillpack_V1_MigrateHarnessesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var success: Bool = false

  public var message: String = String()

  public var totalScanned: Int32 = 0

  public var migratedCount: Int32 = 0

  public var alreadyCompliantCount: Int32 = 0

  public var migratedNames: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "skillpack.v1"

nonisolated extension Skillpack_V1_MigrateOutcome: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0MIGRATE_OUTCOME_UNSPECIFIED\0\u{1}MIGRATE_OUTCOME_MIGRATED\0\u{1}MIGRATE_OUTCOME_REPLACED_WITH_LINK\0\u{1}MIGRATE_OUTCOME_SKIPPED_ALREADY_LINKED\0\u{1}MIGRATE_OUTCOME_SKIPPED_IP_VIOLATION\0\u{1}MIGRATE_OUTCOME_FAILED\0")
}

nonisolated extension Skillpack_V1_AgentIntegrationType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0AGENT_INTEGRATION_TYPE_UNSPECIFIED\0\u{1}AGENT_INTEGRATION_TYPE_SYMLINK\0\u{1}AGENT_INTEGRATION_TYPE_INDEX_FILE\0")
}

nonisolated extension Skillpack_V1_SyncAgentsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SyncAgentsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}dry_run\0\u{3}no_index\0\u{3}only_agent\0\u{1}namespace\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.dryRun) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.noIndex) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._onlyAgent) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._namespace) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.dryRun != false {
      try visitor.visitSingularBoolField(value: self.dryRun, fieldNumber: 1)
    }
    if self.noIndex != false {
      try visitor.visitSingularBoolField(value: self.noIndex, fieldNumber: 2)
    }
    try { if let v = self._onlyAgent {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._namespace {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_SyncAgentsRequest, rhs: Skillpack_V1_SyncAgentsRequest) -> Bool {
    if lhs.dryRun != rhs.dryRun {return false}
    if lhs.noIndex != rhs.noIndex {return false}
    if lhs._onlyAgent != rhs._onlyAgent {return false}
    if lhs._namespace != rhs._namespace {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_SyncAgentsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SyncAgentsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0\u{3}skills_processed\0\u{3}agent_results\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.skillsProcessed) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.agentResults) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if self.skillsProcessed != 0 {
      try visitor.visitSingularInt32Field(value: self.skillsProcessed, fieldNumber: 3)
    }
    if !self.agentResults.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.agentResults, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_SyncAgentsResponse, rhs: Skillpack_V1_SyncAgentsResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs.skillsProcessed != rhs.skillsProcessed {return false}
    if lhs.agentResults != rhs.agentResults {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_AgentSyncResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AgentSyncResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}agent_name\0\u{1}success\0\u{1}message\0\u{3}skills_synced\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.agentName) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.skillsSynced) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.agentName.isEmpty {
      try visitor.visitSingularStringField(value: self.agentName, fieldNumber: 1)
    }
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 2)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 3)
    }
    if self.skillsSynced != 0 {
      try visitor.visitSingularInt32Field(value: self.skillsSynced, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_AgentSyncResult, rhs: Skillpack_V1_AgentSyncResult) -> Bool {
    if lhs.agentName != rhs.agentName {return false}
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs.skillsSynced != rhs.skillsSynced {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_CheckBoundaryRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CheckBoundaryRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}target_path\0\u{3}skill_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.targetPath) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._skillName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.targetPath.isEmpty {
      try visitor.visitSingularStringField(value: self.targetPath, fieldNumber: 1)
    }
    try { if let v = self._skillName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_CheckBoundaryRequest, rhs: Skillpack_V1_CheckBoundaryRequest) -> Bool {
    if lhs.targetPath != rhs.targetPath {return false}
    if lhs._skillName != rhs._skillName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_CheckBoundaryResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CheckBoundaryResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}is_safe\0\u{1}message\0\u{1}violations\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.isSafe) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.violations) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.isSafe != false {
      try visitor.visitSingularBoolField(value: self.isSafe, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if !self.violations.isEmpty {
      try visitor.visitRepeatedStringField(value: self.violations, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_CheckBoundaryResponse, rhs: Skillpack_V1_CheckBoundaryResponse) -> Bool {
    if lhs.isSafe != rhs.isSafe {return false}
    if lhs.message != rhs.message {return false}
    if lhs.violations != rhs.violations {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_MigrateAllRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MigrateAllRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}canonical_root\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.canonicalRoot) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.canonicalRoot.isEmpty {
      try visitor.visitSingularStringField(value: self.canonicalRoot, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_MigrateAllRequest, rhs: Skillpack_V1_MigrateAllRequest) -> Bool {
    if lhs.canonicalRoot != rhs.canonicalRoot {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_MigrateAllResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MigrateAllResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0\u{1}results\0\u{3}migrated_count\0\u{3}replaced_count\0\u{3}skipped_linked_count\0\u{3}skipped_ip_count\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.results) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.migratedCount) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.replacedCount) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.skippedLinkedCount) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.skippedIpCount) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if !self.results.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.results, fieldNumber: 3)
    }
    if self.migratedCount != 0 {
      try visitor.visitSingularInt32Field(value: self.migratedCount, fieldNumber: 4)
    }
    if self.replacedCount != 0 {
      try visitor.visitSingularInt32Field(value: self.replacedCount, fieldNumber: 5)
    }
    if self.skippedLinkedCount != 0 {
      try visitor.visitSingularInt32Field(value: self.skippedLinkedCount, fieldNumber: 6)
    }
    if self.skippedIpCount != 0 {
      try visitor.visitSingularInt32Field(value: self.skippedIpCount, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_MigrateAllResponse, rhs: Skillpack_V1_MigrateAllResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs.results != rhs.results {return false}
    if lhs.migratedCount != rhs.migratedCount {return false}
    if lhs.replacedCount != rhs.replacedCount {return false}
    if lhs.skippedLinkedCount != rhs.skippedLinkedCount {return false}
    if lhs.skippedIpCount != rhs.skippedIpCount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_MigrateResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MigrateResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}agent_name\0\u{3}skill_name\0\u{3}source_path\0\u{1}outcome\0\u{1}message\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.agentName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.skillName) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.sourcePath) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.outcome) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._message) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.agentName.isEmpty {
      try visitor.visitSingularStringField(value: self.agentName, fieldNumber: 1)
    }
    if !self.skillName.isEmpty {
      try visitor.visitSingularStringField(value: self.skillName, fieldNumber: 2)
    }
    if !self.sourcePath.isEmpty {
      try visitor.visitSingularStringField(value: self.sourcePath, fieldNumber: 3)
    }
    if self.outcome != .unspecified {
      try visitor.visitSingularEnumField(value: self.outcome, fieldNumber: 4)
    }
    try { if let v = self._message {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_MigrateResult, rhs: Skillpack_V1_MigrateResult) -> Bool {
    if lhs.agentName != rhs.agentName {return false}
    if lhs.skillName != rhs.skillName {return false}
    if lhs.sourcePath != rhs.sourcePath {return false}
    if lhs.outcome != rhs.outcome {return false}
    if lhs._message != rhs._message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_ImportSkillRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ImportSkillRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}source_path\0\u{3}target_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.sourcePath) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._targetName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.sourcePath.isEmpty {
      try visitor.visitSingularStringField(value: self.sourcePath, fieldNumber: 1)
    }
    try { if let v = self._targetName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_ImportSkillRequest, rhs: Skillpack_V1_ImportSkillRequest) -> Bool {
    if lhs.sourcePath != rhs.sourcePath {return false}
    if lhs._targetName != rhs._targetName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_ImportSkillResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ImportSkillResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0\u{3}skill_name\0\u{3}canonical_path\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.skillName) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.canonicalPath) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if !self.skillName.isEmpty {
      try visitor.visitSingularStringField(value: self.skillName, fieldNumber: 3)
    }
    if !self.canonicalPath.isEmpty {
      try visitor.visitSingularStringField(value: self.canonicalPath, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_ImportSkillResponse, rhs: Skillpack_V1_ImportSkillResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs.skillName != rhs.skillName {return false}
    if lhs.canonicalPath != rhs.canonicalPath {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_PromoteSkillRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PromoteSkillRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}candidate_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.candidateName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.candidateName.isEmpty {
      try visitor.visitSingularStringField(value: self.candidateName, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_PromoteSkillRequest, rhs: Skillpack_V1_PromoteSkillRequest) -> Bool {
    if lhs.candidateName != rhs.candidateName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_PromoteSkillResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PromoteSkillResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0\u{3}skill_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.skillName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if !self.skillName.isEmpty {
      try visitor.visitSingularStringField(value: self.skillName, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_PromoteSkillResponse, rhs: Skillpack_V1_PromoteSkillResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs.skillName != rhs.skillName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_GetStatusRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetStatusRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_GetStatusRequest, rhs: Skillpack_V1_GetStatusRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_GetStatusResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetStatusResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}canonical_root\0\u{3}total_skills\0\u{3}active_agents\0\u{3}is_healthy\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.canonicalRoot) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.totalSkills) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.activeAgents) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.isHealthy) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.canonicalRoot.isEmpty {
      try visitor.visitSingularStringField(value: self.canonicalRoot, fieldNumber: 1)
    }
    if self.totalSkills != 0 {
      try visitor.visitSingularInt32Field(value: self.totalSkills, fieldNumber: 2)
    }
    if !self.activeAgents.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.activeAgents, fieldNumber: 3)
    }
    if self.isHealthy != false {
      try visitor.visitSingularBoolField(value: self.isHealthy, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_GetStatusResponse, rhs: Skillpack_V1_GetStatusResponse) -> Bool {
    if lhs.canonicalRoot != rhs.canonicalRoot {return false}
    if lhs.totalSkills != rhs.totalSkills {return false}
    if lhs.activeAgents != rhs.activeAgents {return false}
    if lhs.isHealthy != rhs.isHealthy {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_AgentStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AgentStatus"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}path\0\u{3}integration_type\0\u{3}is_active\0\u{3}skills_count\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.path) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.integrationType) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.isActive) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.skillsCount) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.path.isEmpty {
      try visitor.visitSingularStringField(value: self.path, fieldNumber: 2)
    }
    if self.integrationType != .unspecified {
      try visitor.visitSingularEnumField(value: self.integrationType, fieldNumber: 3)
    }
    if self.isActive != false {
      try visitor.visitSingularBoolField(value: self.isActive, fieldNumber: 4)
    }
    if self.skillsCount != 0 {
      try visitor.visitSingularInt32Field(value: self.skillsCount, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_AgentStatus, rhs: Skillpack_V1_AgentStatus) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.path != rhs.path {return false}
    if lhs.integrationType != rhs.integrationType {return false}
    if lhs.isActive != rhs.isActive {return false}
    if lhs.skillsCount != rhs.skillsCount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_SyncEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SyncEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}progress\0\u{1}complete\0\u{1}error\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Skillpack_V1_SyncProgress?
        var hadOneofValue = false
        if let current = self.event {
          hadOneofValue = true
          if case .progress(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.event = .progress(v)
        }
      }()
      case 2: try {
        var v: Skillpack_V1_SyncComplete?
        var hadOneofValue = false
        if let current = self.event {
          hadOneofValue = true
          if case .complete(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.event = .complete(v)
        }
      }()
      case 3: try {
        var v: Skillpack_V1_SyncError?
        var hadOneofValue = false
        if let current = self.event {
          hadOneofValue = true
          if case .error(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.event = .error(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.event {
    case .progress?: try {
      guard case .progress(let v)? = self.event else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .complete?: try {
      guard case .complete(let v)? = self.event else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .error?: try {
      guard case .error(let v)? = self.event else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_SyncEvent, rhs: Skillpack_V1_SyncEvent) -> Bool {
    if lhs.event != rhs.event {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_SyncProgress: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SyncProgress"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}agent_name\0\u{3}skill_name\0\u{1}status\0\u{1}current\0\u{1}total\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.agentName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.skillName) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.status) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.current) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.total) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.agentName.isEmpty {
      try visitor.visitSingularStringField(value: self.agentName, fieldNumber: 1)
    }
    if !self.skillName.isEmpty {
      try visitor.visitSingularStringField(value: self.skillName, fieldNumber: 2)
    }
    if !self.status.isEmpty {
      try visitor.visitSingularStringField(value: self.status, fieldNumber: 3)
    }
    if self.current != 0 {
      try visitor.visitSingularInt32Field(value: self.current, fieldNumber: 4)
    }
    if self.total != 0 {
      try visitor.visitSingularInt32Field(value: self.total, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_SyncProgress, rhs: Skillpack_V1_SyncProgress) -> Bool {
    if lhs.agentName != rhs.agentName {return false}
    if lhs.skillName != rhs.skillName {return false}
    if lhs.status != rhs.status {return false}
    if lhs.current != rhs.current {return false}
    if lhs.total != rhs.total {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_SyncComplete: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SyncComplete"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0\u{3}skills_processed\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.skillsProcessed) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if self.skillsProcessed != 0 {
      try visitor.visitSingularInt32Field(value: self.skillsProcessed, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_SyncComplete, rhs: Skillpack_V1_SyncComplete) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs.skillsProcessed != rhs.skillsProcessed {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_SyncError: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SyncError"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}agent_name\0\u{3}skill_name\0\u{3}error_message\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.agentName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.skillName) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.errorMessage) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.agentName.isEmpty {
      try visitor.visitSingularStringField(value: self.agentName, fieldNumber: 1)
    }
    if !self.skillName.isEmpty {
      try visitor.visitSingularStringField(value: self.skillName, fieldNumber: 2)
    }
    if !self.errorMessage.isEmpty {
      try visitor.visitSingularStringField(value: self.errorMessage, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_SyncError, rhs: Skillpack_V1_SyncError) -> Bool {
    if lhs.agentName != rhs.agentName {return false}
    if lhs.skillName != rhs.skillName {return false}
    if lhs.errorMessage != rhs.errorMessage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_RollbackSyncRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RollbackSyncRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}agent_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._agentName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._agentName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_RollbackSyncRequest, rhs: Skillpack_V1_RollbackSyncRequest) -> Bool {
    if lhs._agentName != rhs._agentName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_RollbackSyncResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RollbackSyncResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0\u{3}restored_agents\0\u{3}removed_skills\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.restoredAgents) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.removedSkills) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if !self.restoredAgents.isEmpty {
      try visitor.visitRepeatedStringField(value: self.restoredAgents, fieldNumber: 3)
    }
    if self.removedSkills != 0 {
      try visitor.visitSingularInt32Field(value: self.removedSkills, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_RollbackSyncResponse, rhs: Skillpack_V1_RollbackSyncResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs.restoredAgents != rhs.restoredAgents {return false}
    if lhs.removedSkills != rhs.removedSkills {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_PackageSkillRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PackageSkillRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}skill_ref\0\u{3}registry_url\0\u{1}namespace\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.skillRef) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._registryURL) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._namespace) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.skillRef.isEmpty {
      try visitor.visitSingularStringField(value: self.skillRef, fieldNumber: 1)
    }
    try { if let v = self._registryURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._namespace {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_PackageSkillRequest, rhs: Skillpack_V1_PackageSkillRequest) -> Bool {
    if lhs.skillRef != rhs.skillRef {return false}
    if lhs._registryURL != rhs._registryURL {return false}
    if lhs._namespace != rhs._namespace {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_PackageSkillResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PackageSkillResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0\u{3}artifact_digest\0\u{3}manifest_url\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.artifactDigest) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.manifestURL) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if !self.artifactDigest.isEmpty {
      try visitor.visitSingularStringField(value: self.artifactDigest, fieldNumber: 3)
    }
    if !self.manifestURL.isEmpty {
      try visitor.visitSingularStringField(value: self.manifestURL, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_PackageSkillResponse, rhs: Skillpack_V1_PackageSkillResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs.artifactDigest != rhs.artifactDigest {return false}
    if lhs.manifestURL != rhs.manifestURL {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_PullSkillRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PullSkillRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}skill_ref\0\u{3}source_registry\0\u{1}namespace\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.skillRef) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.sourceRegistry) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._namespace) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.skillRef.isEmpty {
      try visitor.visitSingularStringField(value: self.skillRef, fieldNumber: 1)
    }
    if !self.sourceRegistry.isEmpty {
      try visitor.visitSingularStringField(value: self.sourceRegistry, fieldNumber: 2)
    }
    try { if let v = self._namespace {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_PullSkillRequest, rhs: Skillpack_V1_PullSkillRequest) -> Bool {
    if lhs.skillRef != rhs.skillRef {return false}
    if lhs.sourceRegistry != rhs.sourceRegistry {return false}
    if lhs._namespace != rhs._namespace {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_PullSkillResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PullSkillResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0\u{3}local_path\0\u{3}skill_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.localPath) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.skillName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if !self.localPath.isEmpty {
      try visitor.visitSingularStringField(value: self.localPath, fieldNumber: 3)
    }
    if !self.skillName.isEmpty {
      try visitor.visitSingularStringField(value: self.skillName, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_PullSkillResponse, rhs: Skillpack_V1_PullSkillResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs.localPath != rhs.localPath {return false}
    if lhs.skillName != rhs.skillName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_MigrateSkillsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MigrateSkillsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}canonical_root\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._canonicalRoot) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._canonicalRoot {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_MigrateSkillsRequest, rhs: Skillpack_V1_MigrateSkillsRequest) -> Bool {
    if lhs._canonicalRoot != rhs._canonicalRoot {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_MigrateSkillsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MigrateSkillsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0\u{3}total_scanned\0\u{3}migrated_count\0\u{3}already_compliant_count\0\u{3}migrated_names\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.totalScanned) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.migratedCount) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.alreadyCompliantCount) }()
      case 6: try { try decoder.decodeRepeatedStringField(value: &self.migratedNames) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if self.totalScanned != 0 {
      try visitor.visitSingularInt32Field(value: self.totalScanned, fieldNumber: 3)
    }
    if self.migratedCount != 0 {
      try visitor.visitSingularInt32Field(value: self.migratedCount, fieldNumber: 4)
    }
    if self.alreadyCompliantCount != 0 {
      try visitor.visitSingularInt32Field(value: self.alreadyCompliantCount, fieldNumber: 5)
    }
    if !self.migratedNames.isEmpty {
      try visitor.visitRepeatedStringField(value: self.migratedNames, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_MigrateSkillsResponse, rhs: Skillpack_V1_MigrateSkillsResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs.totalScanned != rhs.totalScanned {return false}
    if lhs.migratedCount != rhs.migratedCount {return false}
    if lhs.alreadyCompliantCount != rhs.alreadyCompliantCount {return false}
    if lhs.migratedNames != rhs.migratedNames {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_MigrateAgentsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MigrateAgentsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_MigrateAgentsRequest, rhs: Skillpack_V1_MigrateAgentsRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_MigrateAgentsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MigrateAgentsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0\u{3}total_scanned\0\u{3}migrated_count\0\u{3}already_compliant_count\0\u{3}migrated_names\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.totalScanned) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.migratedCount) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.alreadyCompliantCount) }()
      case 6: try { try decoder.decodeRepeatedStringField(value: &self.migratedNames) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if self.totalScanned != 0 {
      try visitor.visitSingularInt32Field(value: self.totalScanned, fieldNumber: 3)
    }
    if self.migratedCount != 0 {
      try visitor.visitSingularInt32Field(value: self.migratedCount, fieldNumber: 4)
    }
    if self.alreadyCompliantCount != 0 {
      try visitor.visitSingularInt32Field(value: self.alreadyCompliantCount, fieldNumber: 5)
    }
    if !self.migratedNames.isEmpty {
      try visitor.visitRepeatedStringField(value: self.migratedNames, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_MigrateAgentsResponse, rhs: Skillpack_V1_MigrateAgentsResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs.totalScanned != rhs.totalScanned {return false}
    if lhs.migratedCount != rhs.migratedCount {return false}
    if lhs.alreadyCompliantCount != rhs.alreadyCompliantCount {return false}
    if lhs.migratedNames != rhs.migratedNames {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_MigrateClaudeAgentsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MigrateClaudeAgentsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}agents_dir\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._agentsDir) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._agentsDir {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_MigrateClaudeAgentsRequest, rhs: Skillpack_V1_MigrateClaudeAgentsRequest) -> Bool {
    if lhs._agentsDir != rhs._agentsDir {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_MigrateClaudeAgentsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MigrateClaudeAgentsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0\u{3}total_scanned\0\u{3}migrated_count\0\u{3}already_compliant_count\0\u{3}migrated_names\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.totalScanned) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.migratedCount) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.alreadyCompliantCount) }()
      case 6: try { try decoder.decodeRepeatedStringField(value: &self.migratedNames) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if self.totalScanned != 0 {
      try visitor.visitSingularInt32Field(value: self.totalScanned, fieldNumber: 3)
    }
    if self.migratedCount != 0 {
      try visitor.visitSingularInt32Field(value: self.migratedCount, fieldNumber: 4)
    }
    if self.alreadyCompliantCount != 0 {
      try visitor.visitSingularInt32Field(value: self.alreadyCompliantCount, fieldNumber: 5)
    }
    if !self.migratedNames.isEmpty {
      try visitor.visitRepeatedStringField(value: self.migratedNames, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_MigrateClaudeAgentsResponse, rhs: Skillpack_V1_MigrateClaudeAgentsResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs.totalScanned != rhs.totalScanned {return false}
    if lhs.migratedCount != rhs.migratedCount {return false}
    if lhs.alreadyCompliantCount != rhs.alreadyCompliantCount {return false}
    if lhs.migratedNames != rhs.migratedNames {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_MigrateHarnessesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MigrateHarnessesRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_MigrateHarnessesRequest, rhs: Skillpack_V1_MigrateHarnessesRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skillpack_V1_MigrateHarnessesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MigrateHarnessesResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0\u{3}total_scanned\0\u{3}migrated_count\0\u{3}already_compliant_count\0\u{3}migrated_names\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.totalScanned) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.migratedCount) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.alreadyCompliantCount) }()
      case 6: try { try decoder.decodeRepeatedStringField(value: &self.migratedNames) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if self.totalScanned != 0 {
      try visitor.visitSingularInt32Field(value: self.totalScanned, fieldNumber: 3)
    }
    if self.migratedCount != 0 {
      try visitor.visitSingularInt32Field(value: self.migratedCount, fieldNumber: 4)
    }
    if self.alreadyCompliantCount != 0 {
      try visitor.visitSingularInt32Field(value: self.alreadyCompliantCount, fieldNumber: 5)
    }
    if !self.migratedNames.isEmpty {
      try visitor.visitRepeatedStringField(value: self.migratedNames, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Skillpack_V1_MigrateHarnessesResponse, rhs: Skillpack_V1_MigrateHarnessesResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs.totalScanned != rhs.totalScanned {return false}
    if lhs.migratedCount != rhs.migratedCount {return false}
    if lhs.alreadyCompliantCount != rhs.alreadyCompliantCount {return false}
    if lhs.migratedNames != rhs.migratedNames {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
