//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: skillpack.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Skillpack_V1_SkillPackServiceClient`, then call methods of this protocol to make API calls.
public protocol Skillpack_V1_SkillPackServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Skillpack_V1_SkillPackServiceClientInterceptorFactoryProtocol? { get }

  func assess(
    _ request: Skillpack_V1_AssessRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_AssessRequest, Skillpack_V1_AssessResponse>

  func grade(
    _ request: Skillpack_V1_GradeRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_GradeRequest, Skillpack_V1_GradeResponse>

  func report(
    _ request: Skillpack_V1_ReportRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_ReportRequest, Skillpack_V1_ReportResponse>

  func assessStream(
    _ request: Skillpack_V1_AssessRequest,
    callOptions: CallOptions?,
    handler: @escaping (Skillpack_V1_AssessEvent) -> Void
  ) -> ServerStreamingCall<Skillpack_V1_AssessRequest, Skillpack_V1_AssessEvent>
}

extension Skillpack_V1_SkillPackServiceClientProtocol {
  public var serviceName: String {
    return "skillpack.v1.SkillPackService"
  }

  /// Assess a skill pack
  ///
  /// - Parameters:
  ///   - request: Request to send to Assess.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func assess(
    _ request: Skillpack_V1_AssessRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_AssessRequest, Skillpack_V1_AssessResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_SkillPackServiceClientMetadata.Methods.assess.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAssessInterceptors() ?? []
    )
  }

  /// Grade a skill pack
  ///
  /// - Parameters:
  ///   - request: Request to send to Grade.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func grade(
    _ request: Skillpack_V1_GradeRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_GradeRequest, Skillpack_V1_GradeResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_SkillPackServiceClientMetadata.Methods.grade.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGradeInterceptors() ?? []
    )
  }

  /// Generate assessment report
  ///
  /// - Parameters:
  ///   - request: Request to send to Report.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func report(
    _ request: Skillpack_V1_ReportRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_ReportRequest, Skillpack_V1_ReportResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_SkillPackServiceClientMetadata.Methods.report.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeReportInterceptors() ?? []
    )
  }

  /// Stream assessment progress
  ///
  /// - Parameters:
  ///   - request: Request to send to AssessStream.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  public func assessStream(
    _ request: Skillpack_V1_AssessRequest,
    callOptions: CallOptions? = nil,
    handler: @escaping (Skillpack_V1_AssessEvent) -> Void
  ) -> ServerStreamingCall<Skillpack_V1_AssessRequest, Skillpack_V1_AssessEvent> {
    return self.makeServerStreamingCall(
      path: Skillpack_V1_SkillPackServiceClientMetadata.Methods.assessStream.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAssessStreamInterceptors() ?? [],
      handler: handler
    )
  }
}

@available(*, deprecated)
extension Skillpack_V1_SkillPackServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Skillpack_V1_SkillPackServiceNIOClient")
public final class Skillpack_V1_SkillPackServiceClient: Skillpack_V1_SkillPackServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Skillpack_V1_SkillPackServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Skillpack_V1_SkillPackServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the skillpack.v1.SkillPackService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Skillpack_V1_SkillPackServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Skillpack_V1_SkillPackServiceNIOClient: Skillpack_V1_SkillPackServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Skillpack_V1_SkillPackServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the skillpack.v1.SkillPackService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Skillpack_V1_SkillPackServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Skillpack_V1_SkillPackServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Skillpack_V1_SkillPackServiceClientInterceptorFactoryProtocol? { get }

  func makeAssessCall(
    _ request: Skillpack_V1_AssessRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_AssessRequest, Skillpack_V1_AssessResponse>

  func makeGradeCall(
    _ request: Skillpack_V1_GradeRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_GradeRequest, Skillpack_V1_GradeResponse>

  func makeReportCall(
    _ request: Skillpack_V1_ReportRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_ReportRequest, Skillpack_V1_ReportResponse>

  func makeAssessStreamCall(
    _ request: Skillpack_V1_AssessRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncServerStreamingCall<Skillpack_V1_AssessRequest, Skillpack_V1_AssessEvent>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Skillpack_V1_SkillPackServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Skillpack_V1_SkillPackServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Skillpack_V1_SkillPackServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeAssessCall(
    _ request: Skillpack_V1_AssessRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_AssessRequest, Skillpack_V1_AssessResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_SkillPackServiceClientMetadata.Methods.assess.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAssessInterceptors() ?? []
    )
  }

  public func makeGradeCall(
    _ request: Skillpack_V1_GradeRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_GradeRequest, Skillpack_V1_GradeResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_SkillPackServiceClientMetadata.Methods.grade.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGradeInterceptors() ?? []
    )
  }

  public func makeReportCall(
    _ request: Skillpack_V1_ReportRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_ReportRequest, Skillpack_V1_ReportResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_SkillPackServiceClientMetadata.Methods.report.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeReportInterceptors() ?? []
    )
  }

  public func makeAssessStreamCall(
    _ request: Skillpack_V1_AssessRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncServerStreamingCall<Skillpack_V1_AssessRequest, Skillpack_V1_AssessEvent> {
    return self.makeAsyncServerStreamingCall(
      path: Skillpack_V1_SkillPackServiceClientMetadata.Methods.assessStream.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAssessStreamInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Skillpack_V1_SkillPackServiceAsyncClientProtocol {
  public func assess(
    _ request: Skillpack_V1_AssessRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_AssessResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_SkillPackServiceClientMetadata.Methods.assess.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAssessInterceptors() ?? []
    )
  }

  public func grade(
    _ request: Skillpack_V1_GradeRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_GradeResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_SkillPackServiceClientMetadata.Methods.grade.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGradeInterceptors() ?? []
    )
  }

  public func report(
    _ request: Skillpack_V1_ReportRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_ReportResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_SkillPackServiceClientMetadata.Methods.report.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeReportInterceptors() ?? []
    )
  }

  public func assessStream(
    _ request: Skillpack_V1_AssessRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Skillpack_V1_AssessEvent> {
    return self.performAsyncServerStreamingCall(
      path: Skillpack_V1_SkillPackServiceClientMetadata.Methods.assessStream.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAssessStreamInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Skillpack_V1_SkillPackServiceAsyncClient: Skillpack_V1_SkillPackServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Skillpack_V1_SkillPackServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Skillpack_V1_SkillPackServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Skillpack_V1_SkillPackServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'assess'.
  func makeAssessInterceptors() -> [ClientInterceptor<Skillpack_V1_AssessRequest, Skillpack_V1_AssessResponse>]

  /// - Returns: Interceptors to use when invoking 'grade'.
  func makeGradeInterceptors() -> [ClientInterceptor<Skillpack_V1_GradeRequest, Skillpack_V1_GradeResponse>]

  /// - Returns: Interceptors to use when invoking 'report'.
  func makeReportInterceptors() -> [ClientInterceptor<Skillpack_V1_ReportRequest, Skillpack_V1_ReportResponse>]

  /// - Returns: Interceptors to use when invoking 'assessStream'.
  func makeAssessStreamInterceptors() -> [ClientInterceptor<Skillpack_V1_AssessRequest, Skillpack_V1_AssessEvent>]
}

public enum Skillpack_V1_SkillPackServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "SkillPackService",
    fullName: "skillpack.v1.SkillPackService",
    methods: [
      Skillpack_V1_SkillPackServiceClientMetadata.Methods.assess,
      Skillpack_V1_SkillPackServiceClientMetadata.Methods.grade,
      Skillpack_V1_SkillPackServiceClientMetadata.Methods.report,
      Skillpack_V1_SkillPackServiceClientMetadata.Methods.assessStream,
    ]
  )

  public enum Methods {
    public static let assess = GRPCMethodDescriptor(
      name: "Assess",
      path: "/skillpack.v1.SkillPackService/Assess",
      type: GRPCCallType.unary
    )

    public static let grade = GRPCMethodDescriptor(
      name: "Grade",
      path: "/skillpack.v1.SkillPackService/Grade",
      type: GRPCCallType.unary
    )

    public static let report = GRPCMethodDescriptor(
      name: "Report",
      path: "/skillpack.v1.SkillPackService/Report",
      type: GRPCCallType.unary
    )

    public static let assessStream = GRPCMethodDescriptor(
      name: "AssessStream",
      path: "/skillpack.v1.SkillPackService/AssessStream",
      type: GRPCCallType.serverStreaming
    )
  }
}

/// Usage: instantiate `Skillpack_V1_IndexServiceClient`, then call methods of this protocol to make API calls.
public protocol Skillpack_V1_IndexServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Skillpack_V1_IndexServiceClientInterceptorFactoryProtocol? { get }

  func createIndex(
    _ request: Skillpack_V1_CreateIndexRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_CreateIndexRequest, Skillpack_V1_CreateIndexResponse>

  func getIndex(
    _ request: Skillpack_V1_GetIndexRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_GetIndexRequest, Skillpack_V1_GetIndexResponse>

  func listIndices(
    _ request: Skillpack_V1_ListIndicesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_ListIndicesRequest, Skillpack_V1_ListIndicesResponse>

  func addConstituent(
    _ request: Skillpack_V1_AddConstituentRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_AddConstituentRequest, Skillpack_V1_AddConstituentResponse>

  func calculateValue(
    _ request: Skillpack_V1_CalculateValueRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_CalculateValueRequest, Skillpack_V1_CalculateValueResponse>

  func getHistory(
    _ request: Skillpack_V1_GetHistoryRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_GetHistoryRequest, Skillpack_V1_GetHistoryResponse>
}

extension Skillpack_V1_IndexServiceClientProtocol {
  public var serviceName: String {
    return "skillpack.v1.IndexService"
  }

  /// Create a new index
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateIndex.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func createIndex(
    _ request: Skillpack_V1_CreateIndexRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_CreateIndexRequest, Skillpack_V1_CreateIndexResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_IndexServiceClientMetadata.Methods.createIndex.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateIndexInterceptors() ?? []
    )
  }

  /// Get index by ID
  ///
  /// - Parameters:
  ///   - request: Request to send to GetIndex.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getIndex(
    _ request: Skillpack_V1_GetIndexRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_GetIndexRequest, Skillpack_V1_GetIndexResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_IndexServiceClientMetadata.Methods.getIndex.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetIndexInterceptors() ?? []
    )
  }

  /// List all indices
  ///
  /// - Parameters:
  ///   - request: Request to send to ListIndices.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listIndices(
    _ request: Skillpack_V1_ListIndicesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_ListIndicesRequest, Skillpack_V1_ListIndicesResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_IndexServiceClientMetadata.Methods.listIndices.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListIndicesInterceptors() ?? []
    )
  }

  /// Add skill to index
  ///
  /// - Parameters:
  ///   - request: Request to send to AddConstituent.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func addConstituent(
    _ request: Skillpack_V1_AddConstituentRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_AddConstituentRequest, Skillpack_V1_AddConstituentResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_IndexServiceClientMetadata.Methods.addConstituent.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAddConstituentInterceptors() ?? []
    )
  }

  /// Calculate current index value
  ///
  /// - Parameters:
  ///   - request: Request to send to CalculateValue.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func calculateValue(
    _ request: Skillpack_V1_CalculateValueRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_CalculateValueRequest, Skillpack_V1_CalculateValueResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_IndexServiceClientMetadata.Methods.calculateValue.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCalculateValueInterceptors() ?? []
    )
  }

  /// Get index history
  ///
  /// - Parameters:
  ///   - request: Request to send to GetHistory.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getHistory(
    _ request: Skillpack_V1_GetHistoryRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_GetHistoryRequest, Skillpack_V1_GetHistoryResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_IndexServiceClientMetadata.Methods.getHistory.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetHistoryInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Skillpack_V1_IndexServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Skillpack_V1_IndexServiceNIOClient")
public final class Skillpack_V1_IndexServiceClient: Skillpack_V1_IndexServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Skillpack_V1_IndexServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Skillpack_V1_IndexServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the skillpack.v1.IndexService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Skillpack_V1_IndexServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Skillpack_V1_IndexServiceNIOClient: Skillpack_V1_IndexServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Skillpack_V1_IndexServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the skillpack.v1.IndexService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Skillpack_V1_IndexServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Skillpack_V1_IndexServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Skillpack_V1_IndexServiceClientInterceptorFactoryProtocol? { get }

  func makeCreateIndexCall(
    _ request: Skillpack_V1_CreateIndexRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_CreateIndexRequest, Skillpack_V1_CreateIndexResponse>

  func makeGetIndexCall(
    _ request: Skillpack_V1_GetIndexRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_GetIndexRequest, Skillpack_V1_GetIndexResponse>

  func makeListIndicesCall(
    _ request: Skillpack_V1_ListIndicesRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_ListIndicesRequest, Skillpack_V1_ListIndicesResponse>

  func makeAddConstituentCall(
    _ request: Skillpack_V1_AddConstituentRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_AddConstituentRequest, Skillpack_V1_AddConstituentResponse>

  func makeCalculateValueCall(
    _ request: Skillpack_V1_CalculateValueRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_CalculateValueRequest, Skillpack_V1_CalculateValueResponse>

  func makeGetHistoryCall(
    _ request: Skillpack_V1_GetHistoryRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_GetHistoryRequest, Skillpack_V1_GetHistoryResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Skillpack_V1_IndexServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Skillpack_V1_IndexServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Skillpack_V1_IndexServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeCreateIndexCall(
    _ request: Skillpack_V1_CreateIndexRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_CreateIndexRequest, Skillpack_V1_CreateIndexResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_IndexServiceClientMetadata.Methods.createIndex.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateIndexInterceptors() ?? []
    )
  }

  public func makeGetIndexCall(
    _ request: Skillpack_V1_GetIndexRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_GetIndexRequest, Skillpack_V1_GetIndexResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_IndexServiceClientMetadata.Methods.getIndex.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetIndexInterceptors() ?? []
    )
  }

  public func makeListIndicesCall(
    _ request: Skillpack_V1_ListIndicesRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_ListIndicesRequest, Skillpack_V1_ListIndicesResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_IndexServiceClientMetadata.Methods.listIndices.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListIndicesInterceptors() ?? []
    )
  }

  public func makeAddConstituentCall(
    _ request: Skillpack_V1_AddConstituentRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_AddConstituentRequest, Skillpack_V1_AddConstituentResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_IndexServiceClientMetadata.Methods.addConstituent.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAddConstituentInterceptors() ?? []
    )
  }

  public func makeCalculateValueCall(
    _ request: Skillpack_V1_CalculateValueRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_CalculateValueRequest, Skillpack_V1_CalculateValueResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_IndexServiceClientMetadata.Methods.calculateValue.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCalculateValueInterceptors() ?? []
    )
  }

  public func makeGetHistoryCall(
    _ request: Skillpack_V1_GetHistoryRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_GetHistoryRequest, Skillpack_V1_GetHistoryResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_IndexServiceClientMetadata.Methods.getHistory.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetHistoryInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Skillpack_V1_IndexServiceAsyncClientProtocol {
  public func createIndex(
    _ request: Skillpack_V1_CreateIndexRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_CreateIndexResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_IndexServiceClientMetadata.Methods.createIndex.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateIndexInterceptors() ?? []
    )
  }

  public func getIndex(
    _ request: Skillpack_V1_GetIndexRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_GetIndexResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_IndexServiceClientMetadata.Methods.getIndex.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetIndexInterceptors() ?? []
    )
  }

  public func listIndices(
    _ request: Skillpack_V1_ListIndicesRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_ListIndicesResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_IndexServiceClientMetadata.Methods.listIndices.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListIndicesInterceptors() ?? []
    )
  }

  public func addConstituent(
    _ request: Skillpack_V1_AddConstituentRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_AddConstituentResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_IndexServiceClientMetadata.Methods.addConstituent.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAddConstituentInterceptors() ?? []
    )
  }

  public func calculateValue(
    _ request: Skillpack_V1_CalculateValueRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_CalculateValueResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_IndexServiceClientMetadata.Methods.calculateValue.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCalculateValueInterceptors() ?? []
    )
  }

  public func getHistory(
    _ request: Skillpack_V1_GetHistoryRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_GetHistoryResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_IndexServiceClientMetadata.Methods.getHistory.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetHistoryInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Skillpack_V1_IndexServiceAsyncClient: Skillpack_V1_IndexServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Skillpack_V1_IndexServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Skillpack_V1_IndexServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Skillpack_V1_IndexServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'createIndex'.
  func makeCreateIndexInterceptors() -> [ClientInterceptor<Skillpack_V1_CreateIndexRequest, Skillpack_V1_CreateIndexResponse>]

  /// - Returns: Interceptors to use when invoking 'getIndex'.
  func makeGetIndexInterceptors() -> [ClientInterceptor<Skillpack_V1_GetIndexRequest, Skillpack_V1_GetIndexResponse>]

  /// - Returns: Interceptors to use when invoking 'listIndices'.
  func makeListIndicesInterceptors() -> [ClientInterceptor<Skillpack_V1_ListIndicesRequest, Skillpack_V1_ListIndicesResponse>]

  /// - Returns: Interceptors to use when invoking 'addConstituent'.
  func makeAddConstituentInterceptors() -> [ClientInterceptor<Skillpack_V1_AddConstituentRequest, Skillpack_V1_AddConstituentResponse>]

  /// - Returns: Interceptors to use when invoking 'calculateValue'.
  func makeCalculateValueInterceptors() -> [ClientInterceptor<Skillpack_V1_CalculateValueRequest, Skillpack_V1_CalculateValueResponse>]

  /// - Returns: Interceptors to use when invoking 'getHistory'.
  func makeGetHistoryInterceptors() -> [ClientInterceptor<Skillpack_V1_GetHistoryRequest, Skillpack_V1_GetHistoryResponse>]
}

public enum Skillpack_V1_IndexServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "IndexService",
    fullName: "skillpack.v1.IndexService",
    methods: [
      Skillpack_V1_IndexServiceClientMetadata.Methods.createIndex,
      Skillpack_V1_IndexServiceClientMetadata.Methods.getIndex,
      Skillpack_V1_IndexServiceClientMetadata.Methods.listIndices,
      Skillpack_V1_IndexServiceClientMetadata.Methods.addConstituent,
      Skillpack_V1_IndexServiceClientMetadata.Methods.calculateValue,
      Skillpack_V1_IndexServiceClientMetadata.Methods.getHistory,
    ]
  )

  public enum Methods {
    public static let createIndex = GRPCMethodDescriptor(
      name: "CreateIndex",
      path: "/skillpack.v1.IndexService/CreateIndex",
      type: GRPCCallType.unary
    )

    public static let getIndex = GRPCMethodDescriptor(
      name: "GetIndex",
      path: "/skillpack.v1.IndexService/GetIndex",
      type: GRPCCallType.unary
    )

    public static let listIndices = GRPCMethodDescriptor(
      name: "ListIndices",
      path: "/skillpack.v1.IndexService/ListIndices",
      type: GRPCCallType.unary
    )

    public static let addConstituent = GRPCMethodDescriptor(
      name: "AddConstituent",
      path: "/skillpack.v1.IndexService/AddConstituent",
      type: GRPCCallType.unary
    )

    public static let calculateValue = GRPCMethodDescriptor(
      name: "CalculateValue",
      path: "/skillpack.v1.IndexService/CalculateValue",
      type: GRPCCallType.unary
    )

    public static let getHistory = GRPCMethodDescriptor(
      name: "GetHistory",
      path: "/skillpack.v1.IndexService/GetHistory",
      type: GRPCCallType.unary
    )
  }
}

/// Usage: instantiate `Skillpack_V1_RatingsServiceClient`, then call methods of this protocol to make API calls.
public protocol Skillpack_V1_RatingsServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Skillpack_V1_RatingsServiceClientInterceptorFactoryProtocol? { get }

  func getRating(
    _ request: Skillpack_V1_GetRatingRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_GetRatingRequest, Skillpack_V1_GetRatingResponse>

  func getRatingHistory(
    _ request: Skillpack_V1_GetRatingHistoryRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_GetRatingHistoryRequest, Skillpack_V1_GetRatingHistoryResponse>

  func compareRatings(
    _ request: Skillpack_V1_CompareRatingsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_CompareRatingsRequest, Skillpack_V1_CompareRatingsResponse>
}

extension Skillpack_V1_RatingsServiceClientProtocol {
  public var serviceName: String {
    return "skillpack.v1.RatingsService"
  }

  /// Get skill rating
  ///
  /// - Parameters:
  ///   - request: Request to send to GetRating.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getRating(
    _ request: Skillpack_V1_GetRatingRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_GetRatingRequest, Skillpack_V1_GetRatingResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_RatingsServiceClientMetadata.Methods.getRating.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetRatingInterceptors() ?? []
    )
  }

  /// Get rating history
  ///
  /// - Parameters:
  ///   - request: Request to send to GetRatingHistory.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getRatingHistory(
    _ request: Skillpack_V1_GetRatingHistoryRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_GetRatingHistoryRequest, Skillpack_V1_GetRatingHistoryResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_RatingsServiceClientMetadata.Methods.getRatingHistory.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetRatingHistoryInterceptors() ?? []
    )
  }

  /// Compare ratings
  ///
  /// - Parameters:
  ///   - request: Request to send to CompareRatings.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func compareRatings(
    _ request: Skillpack_V1_CompareRatingsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_CompareRatingsRequest, Skillpack_V1_CompareRatingsResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_RatingsServiceClientMetadata.Methods.compareRatings.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCompareRatingsInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Skillpack_V1_RatingsServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Skillpack_V1_RatingsServiceNIOClient")
public final class Skillpack_V1_RatingsServiceClient: Skillpack_V1_RatingsServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Skillpack_V1_RatingsServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Skillpack_V1_RatingsServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the skillpack.v1.RatingsService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Skillpack_V1_RatingsServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Skillpack_V1_RatingsServiceNIOClient: Skillpack_V1_RatingsServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Skillpack_V1_RatingsServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the skillpack.v1.RatingsService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Skillpack_V1_RatingsServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Skillpack_V1_RatingsServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Skillpack_V1_RatingsServiceClientInterceptorFactoryProtocol? { get }

  func makeGetRatingCall(
    _ request: Skillpack_V1_GetRatingRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_GetRatingRequest, Skillpack_V1_GetRatingResponse>

  func makeGetRatingHistoryCall(
    _ request: Skillpack_V1_GetRatingHistoryRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_GetRatingHistoryRequest, Skillpack_V1_GetRatingHistoryResponse>

  func makeCompareRatingsCall(
    _ request: Skillpack_V1_CompareRatingsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_CompareRatingsRequest, Skillpack_V1_CompareRatingsResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Skillpack_V1_RatingsServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Skillpack_V1_RatingsServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Skillpack_V1_RatingsServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeGetRatingCall(
    _ request: Skillpack_V1_GetRatingRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_GetRatingRequest, Skillpack_V1_GetRatingResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_RatingsServiceClientMetadata.Methods.getRating.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetRatingInterceptors() ?? []
    )
  }

  public func makeGetRatingHistoryCall(
    _ request: Skillpack_V1_GetRatingHistoryRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_GetRatingHistoryRequest, Skillpack_V1_GetRatingHistoryResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_RatingsServiceClientMetadata.Methods.getRatingHistory.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetRatingHistoryInterceptors() ?? []
    )
  }

  public func makeCompareRatingsCall(
    _ request: Skillpack_V1_CompareRatingsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_CompareRatingsRequest, Skillpack_V1_CompareRatingsResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_RatingsServiceClientMetadata.Methods.compareRatings.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCompareRatingsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Skillpack_V1_RatingsServiceAsyncClientProtocol {
  public func getRating(
    _ request: Skillpack_V1_GetRatingRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_GetRatingResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_RatingsServiceClientMetadata.Methods.getRating.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetRatingInterceptors() ?? []
    )
  }

  public func getRatingHistory(
    _ request: Skillpack_V1_GetRatingHistoryRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_GetRatingHistoryResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_RatingsServiceClientMetadata.Methods.getRatingHistory.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetRatingHistoryInterceptors() ?? []
    )
  }

  public func compareRatings(
    _ request: Skillpack_V1_CompareRatingsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_CompareRatingsResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_RatingsServiceClientMetadata.Methods.compareRatings.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCompareRatingsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Skillpack_V1_RatingsServiceAsyncClient: Skillpack_V1_RatingsServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Skillpack_V1_RatingsServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Skillpack_V1_RatingsServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Skillpack_V1_RatingsServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'getRating'.
  func makeGetRatingInterceptors() -> [ClientInterceptor<Skillpack_V1_GetRatingRequest, Skillpack_V1_GetRatingResponse>]

  /// - Returns: Interceptors to use when invoking 'getRatingHistory'.
  func makeGetRatingHistoryInterceptors() -> [ClientInterceptor<Skillpack_V1_GetRatingHistoryRequest, Skillpack_V1_GetRatingHistoryResponse>]

  /// - Returns: Interceptors to use when invoking 'compareRatings'.
  func makeCompareRatingsInterceptors() -> [ClientInterceptor<Skillpack_V1_CompareRatingsRequest, Skillpack_V1_CompareRatingsResponse>]
}

public enum Skillpack_V1_RatingsServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "RatingsService",
    fullName: "skillpack.v1.RatingsService",
    methods: [
      Skillpack_V1_RatingsServiceClientMetadata.Methods.getRating,
      Skillpack_V1_RatingsServiceClientMetadata.Methods.getRatingHistory,
      Skillpack_V1_RatingsServiceClientMetadata.Methods.compareRatings,
    ]
  )

  public enum Methods {
    public static let getRating = GRPCMethodDescriptor(
      name: "GetRating",
      path: "/skillpack.v1.RatingsService/GetRating",
      type: GRPCCallType.unary
    )

    public static let getRatingHistory = GRPCMethodDescriptor(
      name: "GetRatingHistory",
      path: "/skillpack.v1.RatingsService/GetRatingHistory",
      type: GRPCCallType.unary
    )

    public static let compareRatings = GRPCMethodDescriptor(
      name: "CompareRatings",
      path: "/skillpack.v1.RatingsService/CompareRatings",
      type: GRPCCallType.unary
    )
  }
}

/// Usage: instantiate `Skillpack_V1_QueryServiceClient`, then call methods of this protocol to make API calls.
public protocol Skillpack_V1_QueryServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Skillpack_V1_QueryServiceClientInterceptorFactoryProtocol? { get }

  func search(
    _ request: Skillpack_V1_SearchRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_SearchRequest, Skillpack_V1_SearchResponse>

  func getSkillProfile(
    _ request: Skillpack_V1_GetSkillProfileRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_GetSkillProfileRequest, Skillpack_V1_GetSkillProfileResponse>

  func getCompatibility(
    _ request: Skillpack_V1_GetCompatibilityRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_GetCompatibilityRequest, Skillpack_V1_GetCompatibilityResponse>

  func getCostEstimate(
    _ request: Skillpack_V1_GetCostEstimateRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skillpack_V1_GetCostEstimateRequest, Skillpack_V1_GetCostEstimateResponse>
}

extension Skillpack_V1_QueryServiceClientProtocol {
  public var serviceName: String {
    return "skillpack.v1.QueryService"
  }

  /// Search skills with filters
  ///
  /// - Parameters:
  ///   - request: Request to send to Search.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func search(
    _ request: Skillpack_V1_SearchRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_SearchRequest, Skillpack_V1_SearchResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_QueryServiceClientMetadata.Methods.search.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchInterceptors() ?? []
    )
  }

  /// Get skill profile (full details)
  ///
  /// - Parameters:
  ///   - request: Request to send to GetSkillProfile.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getSkillProfile(
    _ request: Skillpack_V1_GetSkillProfileRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_GetSkillProfileRequest, Skillpack_V1_GetSkillProfileResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_QueryServiceClientMetadata.Methods.getSkillProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetSkillProfileInterceptors() ?? []
    )
  }

  /// Get CanIUse compatibility
  ///
  /// - Parameters:
  ///   - request: Request to send to GetCompatibility.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getCompatibility(
    _ request: Skillpack_V1_GetCompatibilityRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_GetCompatibilityRequest, Skillpack_V1_GetCompatibilityResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_QueryServiceClientMetadata.Methods.getCompatibility.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetCompatibilityInterceptors() ?? []
    )
  }

  /// Get cost estimate
  ///
  /// - Parameters:
  ///   - request: Request to send to GetCostEstimate.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getCostEstimate(
    _ request: Skillpack_V1_GetCostEstimateRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skillpack_V1_GetCostEstimateRequest, Skillpack_V1_GetCostEstimateResponse> {
    return self.makeUnaryCall(
      path: Skillpack_V1_QueryServiceClientMetadata.Methods.getCostEstimate.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetCostEstimateInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Skillpack_V1_QueryServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Skillpack_V1_QueryServiceNIOClient")
public final class Skillpack_V1_QueryServiceClient: Skillpack_V1_QueryServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Skillpack_V1_QueryServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Skillpack_V1_QueryServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the skillpack.v1.QueryService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Skillpack_V1_QueryServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Skillpack_V1_QueryServiceNIOClient: Skillpack_V1_QueryServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Skillpack_V1_QueryServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the skillpack.v1.QueryService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Skillpack_V1_QueryServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Skillpack_V1_QueryServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Skillpack_V1_QueryServiceClientInterceptorFactoryProtocol? { get }

  func makeSearchCall(
    _ request: Skillpack_V1_SearchRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_SearchRequest, Skillpack_V1_SearchResponse>

  func makeGetSkillProfileCall(
    _ request: Skillpack_V1_GetSkillProfileRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_GetSkillProfileRequest, Skillpack_V1_GetSkillProfileResponse>

  func makeGetCompatibilityCall(
    _ request: Skillpack_V1_GetCompatibilityRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_GetCompatibilityRequest, Skillpack_V1_GetCompatibilityResponse>

  func makeGetCostEstimateCall(
    _ request: Skillpack_V1_GetCostEstimateRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_GetCostEstimateRequest, Skillpack_V1_GetCostEstimateResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Skillpack_V1_QueryServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Skillpack_V1_QueryServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Skillpack_V1_QueryServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeSearchCall(
    _ request: Skillpack_V1_SearchRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_SearchRequest, Skillpack_V1_SearchResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_QueryServiceClientMetadata.Methods.search.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchInterceptors() ?? []
    )
  }

  public func makeGetSkillProfileCall(
    _ request: Skillpack_V1_GetSkillProfileRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_GetSkillProfileRequest, Skillpack_V1_GetSkillProfileResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_QueryServiceClientMetadata.Methods.getSkillProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetSkillProfileInterceptors() ?? []
    )
  }

  public func makeGetCompatibilityCall(
    _ request: Skillpack_V1_GetCompatibilityRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_GetCompatibilityRequest, Skillpack_V1_GetCompatibilityResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_QueryServiceClientMetadata.Methods.getCompatibility.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetCompatibilityInterceptors() ?? []
    )
  }

  public func makeGetCostEstimateCall(
    _ request: Skillpack_V1_GetCostEstimateRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skillpack_V1_GetCostEstimateRequest, Skillpack_V1_GetCostEstimateResponse> {
    return self.makeAsyncUnaryCall(
      path: Skillpack_V1_QueryServiceClientMetadata.Methods.getCostEstimate.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetCostEstimateInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Skillpack_V1_QueryServiceAsyncClientProtocol {
  public func search(
    _ request: Skillpack_V1_SearchRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_SearchResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_QueryServiceClientMetadata.Methods.search.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchInterceptors() ?? []
    )
  }

  public func getSkillProfile(
    _ request: Skillpack_V1_GetSkillProfileRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_GetSkillProfileResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_QueryServiceClientMetadata.Methods.getSkillProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetSkillProfileInterceptors() ?? []
    )
  }

  public func getCompatibility(
    _ request: Skillpack_V1_GetCompatibilityRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_GetCompatibilityResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_QueryServiceClientMetadata.Methods.getCompatibility.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetCompatibilityInterceptors() ?? []
    )
  }

  public func getCostEstimate(
    _ request: Skillpack_V1_GetCostEstimateRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skillpack_V1_GetCostEstimateResponse {
    return try await self.performAsyncUnaryCall(
      path: Skillpack_V1_QueryServiceClientMetadata.Methods.getCostEstimate.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetCostEstimateInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Skillpack_V1_QueryServiceAsyncClient: Skillpack_V1_QueryServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Skillpack_V1_QueryServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Skillpack_V1_QueryServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Skillpack_V1_QueryServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'search'.
  func makeSearchInterceptors() -> [ClientInterceptor<Skillpack_V1_SearchRequest, Skillpack_V1_SearchResponse>]

  /// - Returns: Interceptors to use when invoking 'getSkillProfile'.
  func makeGetSkillProfileInterceptors() -> [ClientInterceptor<Skillpack_V1_GetSkillProfileRequest, Skillpack_V1_GetSkillProfileResponse>]

  /// - Returns: Interceptors to use when invoking 'getCompatibility'.
  func makeGetCompatibilityInterceptors() -> [ClientInterceptor<Skillpack_V1_GetCompatibilityRequest, Skillpack_V1_GetCompatibilityResponse>]

  /// - Returns: Interceptors to use when invoking 'getCostEstimate'.
  func makeGetCostEstimateInterceptors() -> [ClientInterceptor<Skillpack_V1_GetCostEstimateRequest, Skillpack_V1_GetCostEstimateResponse>]
}

public enum Skillpack_V1_QueryServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "QueryService",
    fullName: "skillpack.v1.QueryService",
    methods: [
      Skillpack_V1_QueryServiceClientMetadata.Methods.search,
      Skillpack_V1_QueryServiceClientMetadata.Methods.getSkillProfile,
      Skillpack_V1_QueryServiceClientMetadata.Methods.getCompatibility,
      Skillpack_V1_QueryServiceClientMetadata.Methods.getCostEstimate,
    ]
  )

  public enum Methods {
    public static let search = GRPCMethodDescriptor(
      name: "Search",
      path: "/skillpack.v1.QueryService/Search",
      type: GRPCCallType.unary
    )

    public static let getSkillProfile = GRPCMethodDescriptor(
      name: "GetSkillProfile",
      path: "/skillpack.v1.QueryService/GetSkillProfile",
      type: GRPCCallType.unary
    )

    public static let getCompatibility = GRPCMethodDescriptor(
      name: "GetCompatibility",
      path: "/skillpack.v1.QueryService/GetCompatibility",
      type: GRPCCallType.unary
    )

    public static let getCostEstimate = GRPCMethodDescriptor(
      name: "GetCostEstimate",
      path: "/skillpack.v1.QueryService/GetCostEstimate",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Skillpack_V1_SkillPackServiceProvider: CallHandlerProvider {
  var interceptors: Skillpack_V1_SkillPackServiceServerInterceptorFactoryProtocol? { get }

  /// Assess a skill pack
  func assess(request: Skillpack_V1_AssessRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_AssessResponse>

  /// Grade a skill pack
  func grade(request: Skillpack_V1_GradeRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_GradeResponse>

  /// Generate assessment report
  func report(request: Skillpack_V1_ReportRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_ReportResponse>

  /// Stream assessment progress
  func assessStream(request: Skillpack_V1_AssessRequest, context: StreamingResponseCallContext<Skillpack_V1_AssessEvent>) -> EventLoopFuture<GRPCStatus>
}

extension Skillpack_V1_SkillPackServiceProvider {
  public var serviceName: Substring {
    return Skillpack_V1_SkillPackServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Assess":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_AssessRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_AssessResponse>(),
        interceptors: self.interceptors?.makeAssessInterceptors() ?? [],
        userFunction: self.assess(request:context:)
      )

    case "Grade":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_GradeRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_GradeResponse>(),
        interceptors: self.interceptors?.makeGradeInterceptors() ?? [],
        userFunction: self.grade(request:context:)
      )

    case "Report":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_ReportRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_ReportResponse>(),
        interceptors: self.interceptors?.makeReportInterceptors() ?? [],
        userFunction: self.report(request:context:)
      )

    case "AssessStream":
      return ServerStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_AssessRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_AssessEvent>(),
        interceptors: self.interceptors?.makeAssessStreamInterceptors() ?? [],
        userFunction: self.assessStream(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Skillpack_V1_SkillPackServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Skillpack_V1_SkillPackServiceServerInterceptorFactoryProtocol? { get }

  /// Assess a skill pack
  func assess(
    request: Skillpack_V1_AssessRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_AssessResponse

  /// Grade a skill pack
  func grade(
    request: Skillpack_V1_GradeRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_GradeResponse

  /// Generate assessment report
  func report(
    request: Skillpack_V1_ReportRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_ReportResponse

  /// Stream assessment progress
  func assessStream(
    request: Skillpack_V1_AssessRequest,
    responseStream: GRPCAsyncResponseStreamWriter<Skillpack_V1_AssessEvent>,
    context: GRPCAsyncServerCallContext
  ) async throws
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Skillpack_V1_SkillPackServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Skillpack_V1_SkillPackServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Skillpack_V1_SkillPackServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Skillpack_V1_SkillPackServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Assess":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_AssessRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_AssessResponse>(),
        interceptors: self.interceptors?.makeAssessInterceptors() ?? [],
        wrapping: { try await self.assess(request: $0, context: $1) }
      )

    case "Grade":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_GradeRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_GradeResponse>(),
        interceptors: self.interceptors?.makeGradeInterceptors() ?? [],
        wrapping: { try await self.grade(request: $0, context: $1) }
      )

    case "Report":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_ReportRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_ReportResponse>(),
        interceptors: self.interceptors?.makeReportInterceptors() ?? [],
        wrapping: { try await self.report(request: $0, context: $1) }
      )

    case "AssessStream":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_AssessRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_AssessEvent>(),
        interceptors: self.interceptors?.makeAssessStreamInterceptors() ?? [],
        wrapping: { try await self.assessStream(request: $0, responseStream: $1, context: $2) }
      )

    default:
      return nil
    }
  }
}

public protocol Skillpack_V1_SkillPackServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'assess'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeAssessInterceptors() -> [ServerInterceptor<Skillpack_V1_AssessRequest, Skillpack_V1_AssessResponse>]

  /// - Returns: Interceptors to use when handling 'grade'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGradeInterceptors() -> [ServerInterceptor<Skillpack_V1_GradeRequest, Skillpack_V1_GradeResponse>]

  /// - Returns: Interceptors to use when handling 'report'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeReportInterceptors() -> [ServerInterceptor<Skillpack_V1_ReportRequest, Skillpack_V1_ReportResponse>]

  /// - Returns: Interceptors to use when handling 'assessStream'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeAssessStreamInterceptors() -> [ServerInterceptor<Skillpack_V1_AssessRequest, Skillpack_V1_AssessEvent>]
}

public enum Skillpack_V1_SkillPackServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "SkillPackService",
    fullName: "skillpack.v1.SkillPackService",
    methods: [
      Skillpack_V1_SkillPackServiceServerMetadata.Methods.assess,
      Skillpack_V1_SkillPackServiceServerMetadata.Methods.grade,
      Skillpack_V1_SkillPackServiceServerMetadata.Methods.report,
      Skillpack_V1_SkillPackServiceServerMetadata.Methods.assessStream,
    ]
  )

  public enum Methods {
    public static let assess = GRPCMethodDescriptor(
      name: "Assess",
      path: "/skillpack.v1.SkillPackService/Assess",
      type: GRPCCallType.unary
    )

    public static let grade = GRPCMethodDescriptor(
      name: "Grade",
      path: "/skillpack.v1.SkillPackService/Grade",
      type: GRPCCallType.unary
    )

    public static let report = GRPCMethodDescriptor(
      name: "Report",
      path: "/skillpack.v1.SkillPackService/Report",
      type: GRPCCallType.unary
    )

    public static let assessStream = GRPCMethodDescriptor(
      name: "AssessStream",
      path: "/skillpack.v1.SkillPackService/AssessStream",
      type: GRPCCallType.serverStreaming
    )
  }
}
/// To build a server, implement a class that conforms to this protocol.
public protocol Skillpack_V1_IndexServiceProvider: CallHandlerProvider {
  var interceptors: Skillpack_V1_IndexServiceServerInterceptorFactoryProtocol? { get }

  /// Create a new index
  func createIndex(request: Skillpack_V1_CreateIndexRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_CreateIndexResponse>

  /// Get index by ID
  func getIndex(request: Skillpack_V1_GetIndexRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_GetIndexResponse>

  /// List all indices
  func listIndices(request: Skillpack_V1_ListIndicesRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_ListIndicesResponse>

  /// Add skill to index
  func addConstituent(request: Skillpack_V1_AddConstituentRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_AddConstituentResponse>

  /// Calculate current index value
  func calculateValue(request: Skillpack_V1_CalculateValueRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_CalculateValueResponse>

  /// Get index history
  func getHistory(request: Skillpack_V1_GetHistoryRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_GetHistoryResponse>
}

extension Skillpack_V1_IndexServiceProvider {
  public var serviceName: Substring {
    return Skillpack_V1_IndexServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "CreateIndex":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_CreateIndexRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_CreateIndexResponse>(),
        interceptors: self.interceptors?.makeCreateIndexInterceptors() ?? [],
        userFunction: self.createIndex(request:context:)
      )

    case "GetIndex":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_GetIndexRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_GetIndexResponse>(),
        interceptors: self.interceptors?.makeGetIndexInterceptors() ?? [],
        userFunction: self.getIndex(request:context:)
      )

    case "ListIndices":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_ListIndicesRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_ListIndicesResponse>(),
        interceptors: self.interceptors?.makeListIndicesInterceptors() ?? [],
        userFunction: self.listIndices(request:context:)
      )

    case "AddConstituent":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_AddConstituentRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_AddConstituentResponse>(),
        interceptors: self.interceptors?.makeAddConstituentInterceptors() ?? [],
        userFunction: self.addConstituent(request:context:)
      )

    case "CalculateValue":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_CalculateValueRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_CalculateValueResponse>(),
        interceptors: self.interceptors?.makeCalculateValueInterceptors() ?? [],
        userFunction: self.calculateValue(request:context:)
      )

    case "GetHistory":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_GetHistoryRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_GetHistoryResponse>(),
        interceptors: self.interceptors?.makeGetHistoryInterceptors() ?? [],
        userFunction: self.getHistory(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Skillpack_V1_IndexServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Skillpack_V1_IndexServiceServerInterceptorFactoryProtocol? { get }

  /// Create a new index
  func createIndex(
    request: Skillpack_V1_CreateIndexRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_CreateIndexResponse

  /// Get index by ID
  func getIndex(
    request: Skillpack_V1_GetIndexRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_GetIndexResponse

  /// List all indices
  func listIndices(
    request: Skillpack_V1_ListIndicesRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_ListIndicesResponse

  /// Add skill to index
  func addConstituent(
    request: Skillpack_V1_AddConstituentRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_AddConstituentResponse

  /// Calculate current index value
  func calculateValue(
    request: Skillpack_V1_CalculateValueRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_CalculateValueResponse

  /// Get index history
  func getHistory(
    request: Skillpack_V1_GetHistoryRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_GetHistoryResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Skillpack_V1_IndexServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Skillpack_V1_IndexServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Skillpack_V1_IndexServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Skillpack_V1_IndexServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "CreateIndex":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_CreateIndexRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_CreateIndexResponse>(),
        interceptors: self.interceptors?.makeCreateIndexInterceptors() ?? [],
        wrapping: { try await self.createIndex(request: $0, context: $1) }
      )

    case "GetIndex":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_GetIndexRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_GetIndexResponse>(),
        interceptors: self.interceptors?.makeGetIndexInterceptors() ?? [],
        wrapping: { try await self.getIndex(request: $0, context: $1) }
      )

    case "ListIndices":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_ListIndicesRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_ListIndicesResponse>(),
        interceptors: self.interceptors?.makeListIndicesInterceptors() ?? [],
        wrapping: { try await self.listIndices(request: $0, context: $1) }
      )

    case "AddConstituent":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_AddConstituentRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_AddConstituentResponse>(),
        interceptors: self.interceptors?.makeAddConstituentInterceptors() ?? [],
        wrapping: { try await self.addConstituent(request: $0, context: $1) }
      )

    case "CalculateValue":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_CalculateValueRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_CalculateValueResponse>(),
        interceptors: self.interceptors?.makeCalculateValueInterceptors() ?? [],
        wrapping: { try await self.calculateValue(request: $0, context: $1) }
      )

    case "GetHistory":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_GetHistoryRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_GetHistoryResponse>(),
        interceptors: self.interceptors?.makeGetHistoryInterceptors() ?? [],
        wrapping: { try await self.getHistory(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol Skillpack_V1_IndexServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'createIndex'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateIndexInterceptors() -> [ServerInterceptor<Skillpack_V1_CreateIndexRequest, Skillpack_V1_CreateIndexResponse>]

  /// - Returns: Interceptors to use when handling 'getIndex'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetIndexInterceptors() -> [ServerInterceptor<Skillpack_V1_GetIndexRequest, Skillpack_V1_GetIndexResponse>]

  /// - Returns: Interceptors to use when handling 'listIndices'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeListIndicesInterceptors() -> [ServerInterceptor<Skillpack_V1_ListIndicesRequest, Skillpack_V1_ListIndicesResponse>]

  /// - Returns: Interceptors to use when handling 'addConstituent'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeAddConstituentInterceptors() -> [ServerInterceptor<Skillpack_V1_AddConstituentRequest, Skillpack_V1_AddConstituentResponse>]

  /// - Returns: Interceptors to use when handling 'calculateValue'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCalculateValueInterceptors() -> [ServerInterceptor<Skillpack_V1_CalculateValueRequest, Skillpack_V1_CalculateValueResponse>]

  /// - Returns: Interceptors to use when handling 'getHistory'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetHistoryInterceptors() -> [ServerInterceptor<Skillpack_V1_GetHistoryRequest, Skillpack_V1_GetHistoryResponse>]
}

public enum Skillpack_V1_IndexServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "IndexService",
    fullName: "skillpack.v1.IndexService",
    methods: [
      Skillpack_V1_IndexServiceServerMetadata.Methods.createIndex,
      Skillpack_V1_IndexServiceServerMetadata.Methods.getIndex,
      Skillpack_V1_IndexServiceServerMetadata.Methods.listIndices,
      Skillpack_V1_IndexServiceServerMetadata.Methods.addConstituent,
      Skillpack_V1_IndexServiceServerMetadata.Methods.calculateValue,
      Skillpack_V1_IndexServiceServerMetadata.Methods.getHistory,
    ]
  )

  public enum Methods {
    public static let createIndex = GRPCMethodDescriptor(
      name: "CreateIndex",
      path: "/skillpack.v1.IndexService/CreateIndex",
      type: GRPCCallType.unary
    )

    public static let getIndex = GRPCMethodDescriptor(
      name: "GetIndex",
      path: "/skillpack.v1.IndexService/GetIndex",
      type: GRPCCallType.unary
    )

    public static let listIndices = GRPCMethodDescriptor(
      name: "ListIndices",
      path: "/skillpack.v1.IndexService/ListIndices",
      type: GRPCCallType.unary
    )

    public static let addConstituent = GRPCMethodDescriptor(
      name: "AddConstituent",
      path: "/skillpack.v1.IndexService/AddConstituent",
      type: GRPCCallType.unary
    )

    public static let calculateValue = GRPCMethodDescriptor(
      name: "CalculateValue",
      path: "/skillpack.v1.IndexService/CalculateValue",
      type: GRPCCallType.unary
    )

    public static let getHistory = GRPCMethodDescriptor(
      name: "GetHistory",
      path: "/skillpack.v1.IndexService/GetHistory",
      type: GRPCCallType.unary
    )
  }
}
/// To build a server, implement a class that conforms to this protocol.
public protocol Skillpack_V1_RatingsServiceProvider: CallHandlerProvider {
  var interceptors: Skillpack_V1_RatingsServiceServerInterceptorFactoryProtocol? { get }

  /// Get skill rating
  func getRating(request: Skillpack_V1_GetRatingRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_GetRatingResponse>

  /// Get rating history
  func getRatingHistory(request: Skillpack_V1_GetRatingHistoryRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_GetRatingHistoryResponse>

  /// Compare ratings
  func compareRatings(request: Skillpack_V1_CompareRatingsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_CompareRatingsResponse>
}

extension Skillpack_V1_RatingsServiceProvider {
  public var serviceName: Substring {
    return Skillpack_V1_RatingsServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetRating":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_GetRatingRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_GetRatingResponse>(),
        interceptors: self.interceptors?.makeGetRatingInterceptors() ?? [],
        userFunction: self.getRating(request:context:)
      )

    case "GetRatingHistory":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_GetRatingHistoryRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_GetRatingHistoryResponse>(),
        interceptors: self.interceptors?.makeGetRatingHistoryInterceptors() ?? [],
        userFunction: self.getRatingHistory(request:context:)
      )

    case "CompareRatings":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_CompareRatingsRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_CompareRatingsResponse>(),
        interceptors: self.interceptors?.makeCompareRatingsInterceptors() ?? [],
        userFunction: self.compareRatings(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Skillpack_V1_RatingsServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Skillpack_V1_RatingsServiceServerInterceptorFactoryProtocol? { get }

  /// Get skill rating
  func getRating(
    request: Skillpack_V1_GetRatingRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_GetRatingResponse

  /// Get rating history
  func getRatingHistory(
    request: Skillpack_V1_GetRatingHistoryRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_GetRatingHistoryResponse

  /// Compare ratings
  func compareRatings(
    request: Skillpack_V1_CompareRatingsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_CompareRatingsResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Skillpack_V1_RatingsServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Skillpack_V1_RatingsServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Skillpack_V1_RatingsServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Skillpack_V1_RatingsServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetRating":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_GetRatingRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_GetRatingResponse>(),
        interceptors: self.interceptors?.makeGetRatingInterceptors() ?? [],
        wrapping: { try await self.getRating(request: $0, context: $1) }
      )

    case "GetRatingHistory":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_GetRatingHistoryRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_GetRatingHistoryResponse>(),
        interceptors: self.interceptors?.makeGetRatingHistoryInterceptors() ?? [],
        wrapping: { try await self.getRatingHistory(request: $0, context: $1) }
      )

    case "CompareRatings":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_CompareRatingsRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_CompareRatingsResponse>(),
        interceptors: self.interceptors?.makeCompareRatingsInterceptors() ?? [],
        wrapping: { try await self.compareRatings(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol Skillpack_V1_RatingsServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'getRating'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetRatingInterceptors() -> [ServerInterceptor<Skillpack_V1_GetRatingRequest, Skillpack_V1_GetRatingResponse>]

  /// - Returns: Interceptors to use when handling 'getRatingHistory'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetRatingHistoryInterceptors() -> [ServerInterceptor<Skillpack_V1_GetRatingHistoryRequest, Skillpack_V1_GetRatingHistoryResponse>]

  /// - Returns: Interceptors to use when handling 'compareRatings'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCompareRatingsInterceptors() -> [ServerInterceptor<Skillpack_V1_CompareRatingsRequest, Skillpack_V1_CompareRatingsResponse>]
}

public enum Skillpack_V1_RatingsServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "RatingsService",
    fullName: "skillpack.v1.RatingsService",
    methods: [
      Skillpack_V1_RatingsServiceServerMetadata.Methods.getRating,
      Skillpack_V1_RatingsServiceServerMetadata.Methods.getRatingHistory,
      Skillpack_V1_RatingsServiceServerMetadata.Methods.compareRatings,
    ]
  )

  public enum Methods {
    public static let getRating = GRPCMethodDescriptor(
      name: "GetRating",
      path: "/skillpack.v1.RatingsService/GetRating",
      type: GRPCCallType.unary
    )

    public static let getRatingHistory = GRPCMethodDescriptor(
      name: "GetRatingHistory",
      path: "/skillpack.v1.RatingsService/GetRatingHistory",
      type: GRPCCallType.unary
    )

    public static let compareRatings = GRPCMethodDescriptor(
      name: "CompareRatings",
      path: "/skillpack.v1.RatingsService/CompareRatings",
      type: GRPCCallType.unary
    )
  }
}
/// To build a server, implement a class that conforms to this protocol.
public protocol Skillpack_V1_QueryServiceProvider: CallHandlerProvider {
  var interceptors: Skillpack_V1_QueryServiceServerInterceptorFactoryProtocol? { get }

  /// Search skills with filters
  func search(request: Skillpack_V1_SearchRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_SearchResponse>

  /// Get skill profile (full details)
  func getSkillProfile(request: Skillpack_V1_GetSkillProfileRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_GetSkillProfileResponse>

  /// Get CanIUse compatibility
  func getCompatibility(request: Skillpack_V1_GetCompatibilityRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_GetCompatibilityResponse>

  /// Get cost estimate
  func getCostEstimate(request: Skillpack_V1_GetCostEstimateRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skillpack_V1_GetCostEstimateResponse>
}

extension Skillpack_V1_QueryServiceProvider {
  public var serviceName: Substring {
    return Skillpack_V1_QueryServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Search":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_SearchRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_SearchResponse>(),
        interceptors: self.interceptors?.makeSearchInterceptors() ?? [],
        userFunction: self.search(request:context:)
      )

    case "GetSkillProfile":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_GetSkillProfileRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_GetSkillProfileResponse>(),
        interceptors: self.interceptors?.makeGetSkillProfileInterceptors() ?? [],
        userFunction: self.getSkillProfile(request:context:)
      )

    case "GetCompatibility":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_GetCompatibilityRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_GetCompatibilityResponse>(),
        interceptors: self.interceptors?.makeGetCompatibilityInterceptors() ?? [],
        userFunction: self.getCompatibility(request:context:)
      )

    case "GetCostEstimate":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_GetCostEstimateRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_GetCostEstimateResponse>(),
        interceptors: self.interceptors?.makeGetCostEstimateInterceptors() ?? [],
        userFunction: self.getCostEstimate(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Skillpack_V1_QueryServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Skillpack_V1_QueryServiceServerInterceptorFactoryProtocol? { get }

  /// Search skills with filters
  func search(
    request: Skillpack_V1_SearchRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_SearchResponse

  /// Get skill profile (full details)
  func getSkillProfile(
    request: Skillpack_V1_GetSkillProfileRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_GetSkillProfileResponse

  /// Get CanIUse compatibility
  func getCompatibility(
    request: Skillpack_V1_GetCompatibilityRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_GetCompatibilityResponse

  /// Get cost estimate
  func getCostEstimate(
    request: Skillpack_V1_GetCostEstimateRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skillpack_V1_GetCostEstimateResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Skillpack_V1_QueryServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Skillpack_V1_QueryServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Skillpack_V1_QueryServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Skillpack_V1_QueryServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Search":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_SearchRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_SearchResponse>(),
        interceptors: self.interceptors?.makeSearchInterceptors() ?? [],
        wrapping: { try await self.search(request: $0, context: $1) }
      )

    case "GetSkillProfile":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_GetSkillProfileRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_GetSkillProfileResponse>(),
        interceptors: self.interceptors?.makeGetSkillProfileInterceptors() ?? [],
        wrapping: { try await self.getSkillProfile(request: $0, context: $1) }
      )

    case "GetCompatibility":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_GetCompatibilityRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_GetCompatibilityResponse>(),
        interceptors: self.interceptors?.makeGetCompatibilityInterceptors() ?? [],
        wrapping: { try await self.getCompatibility(request: $0, context: $1) }
      )

    case "GetCostEstimate":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skillpack_V1_GetCostEstimateRequest>(),
        responseSerializer: ProtobufSerializer<Skillpack_V1_GetCostEstimateResponse>(),
        interceptors: self.interceptors?.makeGetCostEstimateInterceptors() ?? [],
        wrapping: { try await self.getCostEstimate(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol Skillpack_V1_QueryServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'search'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSearchInterceptors() -> [ServerInterceptor<Skillpack_V1_SearchRequest, Skillpack_V1_SearchResponse>]

  /// - Returns: Interceptors to use when handling 'getSkillProfile'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetSkillProfileInterceptors() -> [ServerInterceptor<Skillpack_V1_GetSkillProfileRequest, Skillpack_V1_GetSkillProfileResponse>]

  /// - Returns: Interceptors to use when handling 'getCompatibility'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetCompatibilityInterceptors() -> [ServerInterceptor<Skillpack_V1_GetCompatibilityRequest, Skillpack_V1_GetCompatibilityResponse>]

  /// - Returns: Interceptors to use when handling 'getCostEstimate'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetCostEstimateInterceptors() -> [ServerInterceptor<Skillpack_V1_GetCostEstimateRequest, Skillpack_V1_GetCostEstimateResponse>]
}

public enum Skillpack_V1_QueryServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "QueryService",
    fullName: "skillpack.v1.QueryService",
    methods: [
      Skillpack_V1_QueryServiceServerMetadata.Methods.search,
      Skillpack_V1_QueryServiceServerMetadata.Methods.getSkillProfile,
      Skillpack_V1_QueryServiceServerMetadata.Methods.getCompatibility,
      Skillpack_V1_QueryServiceServerMetadata.Methods.getCostEstimate,
    ]
  )

  public enum Methods {
    public static let search = GRPCMethodDescriptor(
      name: "Search",
      path: "/skillpack.v1.QueryService/Search",
      type: GRPCCallType.unary
    )

    public static let getSkillProfile = GRPCMethodDescriptor(
      name: "GetSkillProfile",
      path: "/skillpack.v1.QueryService/GetSkillProfile",
      type: GRPCCallType.unary
    )

    public static let getCompatibility = GRPCMethodDescriptor(
      name: "GetCompatibility",
      path: "/skillpack.v1.QueryService/GetCompatibility",
      type: GRPCCallType.unary
    )

    public static let getCostEstimate = GRPCMethodDescriptor(
      name: "GetCostEstimate",
      path: "/skillpack.v1.QueryService/GetCostEstimate",
      type: GRPCCallType.unary
    )
  }
}
