//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: skills.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Skills_SkillsServiceClient`, then call methods of this protocol to make API calls.
public protocol Skills_SkillsServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Skills_SkillsServiceClientInterceptorFactoryProtocol? { get }

  func syncSkills(
    _ request: Skills_SyncRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skills_SyncRequest, Skills_SyncResponse>

  func getStatus(
    _ request: Skills_StatusRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skills_StatusRequest, Skills_StatusResponse>

  func checkBoundary(
    _ request: Skills_BoundaryRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Skills_BoundaryRequest, Skills_BoundaryResponse>
}

extension Skills_SkillsServiceClientProtocol {
  public var serviceName: String {
    return "skills.SkillsService"
  }

  /// Triggers a full synchronization of skills
  ///
  /// - Parameters:
  ///   - request: Request to send to SyncSkills.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func syncSkills(
    _ request: Skills_SyncRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skills_SyncRequest, Skills_SyncResponse> {
    return self.makeUnaryCall(
      path: Skills_SkillsServiceClientMetadata.Methods.syncSkills.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSyncSkillsInterceptors() ?? []
    )
  }

  /// Gets the current state and number of skills
  ///
  /// - Parameters:
  ///   - request: Request to send to GetStatus.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getStatus(
    _ request: Skills_StatusRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skills_StatusRequest, Skills_StatusResponse> {
    return self.makeUnaryCall(
      path: Skills_SkillsServiceClientMetadata.Methods.getStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetStatusInterceptors() ?? []
    )
  }

  /// Checks if a specific path violates the Thales IP boundary
  ///
  /// - Parameters:
  ///   - request: Request to send to CheckBoundary.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func checkBoundary(
    _ request: Skills_BoundaryRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Skills_BoundaryRequest, Skills_BoundaryResponse> {
    return self.makeUnaryCall(
      path: Skills_SkillsServiceClientMetadata.Methods.checkBoundary.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCheckBoundaryInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Skills_SkillsServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Skills_SkillsServiceNIOClient")
public final class Skills_SkillsServiceClient: Skills_SkillsServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Skills_SkillsServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Skills_SkillsServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the skills.SkillsService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Skills_SkillsServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Skills_SkillsServiceNIOClient: Skills_SkillsServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Skills_SkillsServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the skills.SkillsService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Skills_SkillsServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Skills_SkillsServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Skills_SkillsServiceClientInterceptorFactoryProtocol? { get }

  func makeSyncSkillsCall(
    _ request: Skills_SyncRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skills_SyncRequest, Skills_SyncResponse>

  func makeGetStatusCall(
    _ request: Skills_StatusRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skills_StatusRequest, Skills_StatusResponse>

  func makeCheckBoundaryCall(
    _ request: Skills_BoundaryRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Skills_BoundaryRequest, Skills_BoundaryResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Skills_SkillsServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Skills_SkillsServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Skills_SkillsServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeSyncSkillsCall(
    _ request: Skills_SyncRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skills_SyncRequest, Skills_SyncResponse> {
    return self.makeAsyncUnaryCall(
      path: Skills_SkillsServiceClientMetadata.Methods.syncSkills.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSyncSkillsInterceptors() ?? []
    )
  }

  public func makeGetStatusCall(
    _ request: Skills_StatusRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skills_StatusRequest, Skills_StatusResponse> {
    return self.makeAsyncUnaryCall(
      path: Skills_SkillsServiceClientMetadata.Methods.getStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetStatusInterceptors() ?? []
    )
  }

  public func makeCheckBoundaryCall(
    _ request: Skills_BoundaryRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Skills_BoundaryRequest, Skills_BoundaryResponse> {
    return self.makeAsyncUnaryCall(
      path: Skills_SkillsServiceClientMetadata.Methods.checkBoundary.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCheckBoundaryInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Skills_SkillsServiceAsyncClientProtocol {
  public func syncSkills(
    _ request: Skills_SyncRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skills_SyncResponse {
    return try await self.performAsyncUnaryCall(
      path: Skills_SkillsServiceClientMetadata.Methods.syncSkills.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSyncSkillsInterceptors() ?? []
    )
  }

  public func getStatus(
    _ request: Skills_StatusRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skills_StatusResponse {
    return try await self.performAsyncUnaryCall(
      path: Skills_SkillsServiceClientMetadata.Methods.getStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetStatusInterceptors() ?? []
    )
  }

  public func checkBoundary(
    _ request: Skills_BoundaryRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Skills_BoundaryResponse {
    return try await self.performAsyncUnaryCall(
      path: Skills_SkillsServiceClientMetadata.Methods.checkBoundary.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCheckBoundaryInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Skills_SkillsServiceAsyncClient: Skills_SkillsServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Skills_SkillsServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Skills_SkillsServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Skills_SkillsServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'syncSkills'.
  func makeSyncSkillsInterceptors() -> [ClientInterceptor<Skills_SyncRequest, Skills_SyncResponse>]

  /// - Returns: Interceptors to use when invoking 'getStatus'.
  func makeGetStatusInterceptors() -> [ClientInterceptor<Skills_StatusRequest, Skills_StatusResponse>]

  /// - Returns: Interceptors to use when invoking 'checkBoundary'.
  func makeCheckBoundaryInterceptors() -> [ClientInterceptor<Skills_BoundaryRequest, Skills_BoundaryResponse>]
}

public enum Skills_SkillsServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "SkillsService",
    fullName: "skills.SkillsService",
    methods: [
      Skills_SkillsServiceClientMetadata.Methods.syncSkills,
      Skills_SkillsServiceClientMetadata.Methods.getStatus,
      Skills_SkillsServiceClientMetadata.Methods.checkBoundary,
    ]
  )

  public enum Methods {
    public static let syncSkills = GRPCMethodDescriptor(
      name: "SyncSkills",
      path: "/skills.SkillsService/SyncSkills",
      type: GRPCCallType.unary
    )

    public static let getStatus = GRPCMethodDescriptor(
      name: "GetStatus",
      path: "/skills.SkillsService/GetStatus",
      type: GRPCCallType.unary
    )

    public static let checkBoundary = GRPCMethodDescriptor(
      name: "CheckBoundary",
      path: "/skills.SkillsService/CheckBoundary",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Skills_SkillsServiceProvider: CallHandlerProvider {
  var interceptors: Skills_SkillsServiceServerInterceptorFactoryProtocol? { get }

  /// Triggers a full synchronization of skills
  func syncSkills(request: Skills_SyncRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skills_SyncResponse>

  /// Gets the current state and number of skills
  func getStatus(request: Skills_StatusRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skills_StatusResponse>

  /// Checks if a specific path violates the Thales IP boundary
  func checkBoundary(request: Skills_BoundaryRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Skills_BoundaryResponse>
}

extension Skills_SkillsServiceProvider {
  public var serviceName: Substring {
    return Skills_SkillsServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "SyncSkills":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skills_SyncRequest>(),
        responseSerializer: ProtobufSerializer<Skills_SyncResponse>(),
        interceptors: self.interceptors?.makeSyncSkillsInterceptors() ?? [],
        userFunction: self.syncSkills(request:context:)
      )

    case "GetStatus":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skills_StatusRequest>(),
        responseSerializer: ProtobufSerializer<Skills_StatusResponse>(),
        interceptors: self.interceptors?.makeGetStatusInterceptors() ?? [],
        userFunction: self.getStatus(request:context:)
      )

    case "CheckBoundary":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skills_BoundaryRequest>(),
        responseSerializer: ProtobufSerializer<Skills_BoundaryResponse>(),
        interceptors: self.interceptors?.makeCheckBoundaryInterceptors() ?? [],
        userFunction: self.checkBoundary(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Skills_SkillsServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Skills_SkillsServiceServerInterceptorFactoryProtocol? { get }

  /// Triggers a full synchronization of skills
  func syncSkills(
    request: Skills_SyncRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skills_SyncResponse

  /// Gets the current state and number of skills
  func getStatus(
    request: Skills_StatusRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skills_StatusResponse

  /// Checks if a specific path violates the Thales IP boundary
  func checkBoundary(
    request: Skills_BoundaryRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Skills_BoundaryResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Skills_SkillsServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Skills_SkillsServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Skills_SkillsServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Skills_SkillsServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "SyncSkills":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skills_SyncRequest>(),
        responseSerializer: ProtobufSerializer<Skills_SyncResponse>(),
        interceptors: self.interceptors?.makeSyncSkillsInterceptors() ?? [],
        wrapping: { try await self.syncSkills(request: $0, context: $1) }
      )

    case "GetStatus":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skills_StatusRequest>(),
        responseSerializer: ProtobufSerializer<Skills_StatusResponse>(),
        interceptors: self.interceptors?.makeGetStatusInterceptors() ?? [],
        wrapping: { try await self.getStatus(request: $0, context: $1) }
      )

    case "CheckBoundary":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Skills_BoundaryRequest>(),
        responseSerializer: ProtobufSerializer<Skills_BoundaryResponse>(),
        interceptors: self.interceptors?.makeCheckBoundaryInterceptors() ?? [],
        wrapping: { try await self.checkBoundary(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol Skills_SkillsServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'syncSkills'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSyncSkillsInterceptors() -> [ServerInterceptor<Skills_SyncRequest, Skills_SyncResponse>]

  /// - Returns: Interceptors to use when handling 'getStatus'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetStatusInterceptors() -> [ServerInterceptor<Skills_StatusRequest, Skills_StatusResponse>]

  /// - Returns: Interceptors to use when handling 'checkBoundary'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCheckBoundaryInterceptors() -> [ServerInterceptor<Skills_BoundaryRequest, Skills_BoundaryResponse>]
}

public enum Skills_SkillsServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "SkillsService",
    fullName: "skills.SkillsService",
    methods: [
      Skills_SkillsServiceServerMetadata.Methods.syncSkills,
      Skills_SkillsServiceServerMetadata.Methods.getStatus,
      Skills_SkillsServiceServerMetadata.Methods.checkBoundary,
    ]
  )

  public enum Methods {
    public static let syncSkills = GRPCMethodDescriptor(
      name: "SyncSkills",
      path: "/skills.SkillsService/SyncSkills",
      type: GRPCCallType.unary
    )

    public static let getStatus = GRPCMethodDescriptor(
      name: "GetStatus",
      path: "/skills.SkillsService/GetStatus",
      type: GRPCCallType.unary
    )

    public static let checkBoundary = GRPCMethodDescriptor(
      name: "CheckBoundary",
      path: "/skills.SkillsService/CheckBoundary",
      type: GRPCCallType.unary
    )
  }
}
