import Foundation
import CryptoKit

public struct ManifestGenerator {
    private let fileManager = FileManager.default
    private let skillsRoot: URL
    
    public init(skillsRoot: URL) {
        self.skillsRoot = skillsRoot
    }

    /// T-05: Emit bundle.json — Phase 1 bundle precursor.
    /// Fields: name, sha256 (of manifest.yaml), size, manifest_version, evidence_refs, generated_at.
    public func generateBundleJson(skills: [Skill], manifestURL: URL, outputURL: URL) throws {
        let manifestData = (try? Data(contentsOf: manifestURL)) ?? Data()
        let digest = SHA256.hash(data: manifestData)
        let sha256 = "sha256:" + digest.map { String(format: "%02x", $0) }.joined()

        var skillEntries: [[String: Any]] = []
        for skill in skills {
            skillEntries.append([
                "name": skill.name,
                "size_bytes": skill.sizeBytes,
                "asc": skill.asc,
                "lifecycle": skill.lifecycleStatus.rawValue
            ])
        }

        let bundle: [String: Any] = [
            "manifest_version": 1,
            "name": skillsRoot.lastPathComponent,
            "sha256": sha256,
            "size": manifestData.count,
            "skills": skillEntries,
            "evidence_refs": [],
            "generated_at": ISO8601DateFormatter().string(from: Date())
        ]

        let data = try JSONSerialization.data(withJSONObject: bundle, options: [.prettyPrinted, .sortedKeys])
        try safeAtomicWrite(data: data, to: outputURL)
    }

    public func generateManifest(skills: [Skill], outputURL: URL) throws {
        let dateFormatter = ISO8601DateFormatter()
        let dateString = dateFormatter.string(from: Date())
        
        var content = """
        # Auto-generated by skills-cli. Do not edit by hand.
        generated_at: "\(dateString)"
        canonical_root: "\(skillsRoot.path)"
        skills:\n
        """
        
        for skill in skills {
            content += """
              - name: "\(skill.name)"
                path: "\(skill.url.path)"
                size_bytes: \(skill.sizeBytes)
                description: "\(skill.description)"\n
            """
        }
        
        try safeAtomicWrite(content: content, to: outputURL)
    }
    
    private func safeAtomicWrite(content: String, to url: URL) throws {
        if fileManager.fileExists(atPath: url.path) {
            let tempURL = fileManager.temporaryDirectory.appendingPathComponent(UUID().uuidString)
            try content.write(to: tempURL, atomically: true, encoding: .utf8)
            _ = try fileManager.replaceItemAt(url, withItemAt: tempURL)
        } else {
            try content.write(to: url, atomically: true, encoding: .utf8)
        }
    }

    private func safeAtomicWrite(data: Data, to url: URL) throws {
        if fileManager.fileExists(atPath: url.path) {
            let tempURL = fileManager.temporaryDirectory.appendingPathComponent(UUID().uuidString)
            try data.write(to: tempURL, options: .atomic)
            _ = try fileManager.replaceItemAt(url, withItemAt: tempURL)
        } else {
            try data.write(to: url, options: .atomic)
        }
    }
}
